### ISSUE TITLE
how to backup in plan

### ISSUE THREAD

**Issue by PrestarLin** [007revad/Synology_app_mover#105]
How can I back up a specified kit (such as Photos) in a scheduled task? I know how to perform backup step by step in SSH, but I don't know how to do it in a scheduled plan.
@007revad

**Comment by 007revad** [comment]
I'm working on version 4 that will allow scheduling syno_app_mover to backup apps with a --auto option,

You'll be bale to schedule it as "syno_app_mover.sh --auto="Photos". 

Also in syno_app_mover.conf you will be able to use the auto setting to set which apps to backup:
`auto="all"`
or
`auto="AudioStation,Calendar,Chat,NoteStation"`

As well as an exclude setting for when auto="all" is used:
```
exclude="ContainerManager"
exclude="DownloadStation,ContainerManager,HyperBackup"
```

**Comment by PrestarLin** [comment]
> 我正在开发版本 4，该版本允许使用 --auto 选项安排syno_app_mover备份应用程序，
> 
> 您可以将其安排为“syno_app_mover.sh --auto=”Photos”。
> 
> 此外，在 syno_app_mover.conf 中，您将能够使用自动设置来设置要备份的应用程序： 或`auto="all"` `auto="AudioStation,Calendar,Chat,NoteStation"`
> 
> 以及使用 auto=“all” 时的排除设置：
> 
> ```
> exclude="ContainerManager"
> exclude="DownloadStation,ContainerManager,HyperBackup"
> ```

Thank you~ I am looking forward to it.

**Comment by yilin101** [comment]
I look forward to it too! Great

**Comment by 007revad** [comment]
@PrestarLin @yilin101 

Do you want to try the new release candidate version that can be scheduled to backup apps.
https://github.com/007revad/Synology_app_mover/releases/tag/v4.0.62

**Comment by yilin101** [comment]
> @PrestarLin @yilin101
> 
> Do you want to try the new release candidate version that can be scheduled to backup apps. https://github.com/007revad/Synology_app_mover/releases/tag/v4.0.62

Great, I've been looking forward to when it would be available and was pleasantly surprised that it was so soon.
I'll test it now.
