### ISSUE TITLE
Unable to Backup Container Manager

### ISSUE THREAD

**Issue by joelhinch** [007revad/Synology_app_mover#116]
Hi. Thanks a lot for your work on your scripts. They are a game changer.
I an unable to backup my containers using the script unfortunately. I recieve the below error.

> WARNING Not enough space to backup /volume1/@docker to
> Free: 0 GB  Needed: 190 GB (plus 50 GB buffer)
> 
> ERROR Not enough space on  to backup @docker!

I have 10.5 TB of free space.

Tried moving to another volume (which was succesful) and the same error occured.

**Comment by 007revad** [comment]
Was this when moving Container Manager to another volume? Or when backing up Container Manager to the same volume?

Backing up `/volumeX/@docker` is optional (just in case something goes wrong). It copies the `@docker` folder to `@docker_backup` on the same volume.

Which version of the script did you use? v3.1.60 ?

[v4.0.63-RC](https://github.com/007revad/Synology_app_mover/releases/tag/v4.0.63) includes a bug fix for: 
- Bug fix for error getting size of folder if folder existed but was empty.

which can occur if the script creates the folder before moving the contents.

**Comment by joelhinch** [comment]
@007revad thanks for getting back to me

I am intentionally trying to make a backup (as well as the move)

I am using 4.0.63

**Comment by hdswiss** [comment]
I am getting this error line 1786: package_names["${package_name}"]: bad array subscript

> root@MYNAS:~# /volume1/scripts/syno_app_mover.sh
Synology_app_mover v4.0.63
DS1812+ DSM 6.2.4-25556-7

Running from: /volume1/scripts/syno_app_mover.sh

1) Move
2) Backup
3) Restore
Select the mode: 2
You selected Backup

Backup path is: /volume1/backups

/volume1/scripts/syno_app_mover.sh: **line 1786: package_names["${package_name}"]: bad array subscript**
Do you want to backup All packages? [y/n]

**Comment by 007revad** [comment]
@hdswiss Can you create a new issue for this.

**Comment by joelhinch** [comment]
@007revad FYI
4.0.62 also failed
3.2.61 made it past errors checking free space and started copying data but had warnings

> Backing up /volume1/@apphome/ContainerManager
> \e[0;33mWARNING\e[0m Failed to get size of /volume1/@appshare
> Backing up /volume1/@appshare/ContainerManager
> WARNING Backing up @appstore could take a long time
> Backing up /volume1/@appstore/ContainerManager
> \e[0;33mWARNING\e[0m Failed to get size of /volume1/@apptemp
> Backing up /volume1/@apptemp/ContainerManager

**Comment by 007revad** [comment]
> ERROR Not enough space on to backup @docker!

I see the problem. That error message should be "ERROR Not enough space on **/volume#** to backup `@docker!`"

**/volume#** should not be blank.

**Comment by 007revad** [comment]
I've fixed it in https://github.com/007revad/Synology_app_mover/releases/tag/v4.0.65

**Comment by 007revad** [comment]
FYI there's a newer verison https://github.com/007revad/Synology_app_mover/releases/tag/v4.0.68

**Comment by hdswiss** [comment]
With version v4.0.68-RC works fine many thanks for that
<img width="602" alt="syno_app_mover" src="https://github.com/user-attachments/assets/39b650fe-0518-40ef-85bc-4935d038e214">
