### ISSUE TITLE
Backing Up Docker Failed - File names too long

### ISSUE THREAD

**Issue by stevenhaskell** [007revad/Synology_app_mover#120]
Running into an issue backing up Docker. I'm able to successfully export the container settings and backup Container Manager but when the script starts to backup docker I get errors for multiple files stating the file name is too long and then an error stating backing up docker failed.

The backup volume is using btrfs which has a file name limit of 255 characters. the mentioned files have names ranging from 180-200 characters. 

Any thoughts on how to resolve this?

> Starting Container Manager             
> Waiting for Container Manager to start            
> Exporting container settings to /volume1/docker/app_mover_exports
> Exporting vaultwarden-server json
> Exporting HomeAssistant json
> Exporting gitea json
> Exporting flaresolverr json
> Exporting couchdb json
> Exporting tautulli json
> Exporting sonarr json
> Exporting radarr json
> Exporting Prowlarr json
> Exporting unifi-controller json
> Exporting synology_docviewer_2 json
> Exporting synology_docviewer_1 json
> Exporting penpot-frontend json
> Exporting penpot-backend json
> Exporting penpot-db json
> Exporting penpot-redis json
> Exporting penpot-exporter json
> Exporting haugene-transmission-openvpn json
> Exporting speedtest json
> Exporting Requestrr json
> Exporting wordpress-portfolio-site-phpmyadmin json
> Exporting wordpress-portfolio-site json
> Exporting wordpress-portfolio-site-db json
> Exporting readarr json
> Removing dangling docker images
> Stopping Container Manager             
> Waiting for Container Manager to stop            
> Backing up /volume1/@appconf/ContainerManager            
> Backing up /volume1/@appdata/ContainerManager            
> Backing up /volume1/@apphome/ContainerManager            
> Backing up /volume1/@appshare/ContainerManager            
> Backing up /volume1/@appstore/ContainerManager            
> Backing up /volume1/@apptemp/ContainerManager            
> WARNING Backing up @docker could take a long time
> rsync: mknod "/volume1/Backups/syno_app_mover/ContainerManager/extras/@docker/btrfs/subvolumes/10ca44d29ebd91b7f715325c2efa89992b9618e5eec371e70526077338d84ade/run/s6-rc:s6-rc-init:fKkEBE/servicedirs/s6rc-oneshot-runner/s" failed: File name too long (36)
> rsync: mknod "/volume1/Backups/syno_app_mover/ContainerManager/extras/@docker/btrfs/subvolumes/10ca44d29ebd91b7f715325c2efa89992b9618e5eec371e70526077338d84ade/tmp/dotnet-diagnostic-141-389002210-socket" failed: File name too long (36)
> rsync: mknod "/volume1/Backups/syno_app_mover/ContainerManager/extras/@docker/btrfs/subvolumes/14c5239d91670326ca50114d50db43a6182a29022ed13576dd08be66269e5d72/run/s6-rc:s6-rc-init:LcfPed/servicedirs/s6rc-oneshot-runner/s" failed: File name too long (36)
> rsync: mknod "/volume1/Backups/syno_app_mover/ContainerManager/extras/@docker/btrfs/subvolumes/14c5239d91670326ca50114d50db43a6182a29022ed13576dd08be66269e5d72/tmp/dotnet-diagnostic-137-103454549-socket" failed: File name too long (36)
> rsync: mknod "/volume1/Backups/syno_app_mover/ContainerManager/extras/@docker/btrfs/subvolumes/14c5239d91670326ca50114d50db43a6182a29022ed13576dd08be66269e5d72/tmp/dotnet-diagnostic-137-104473824-socket" failed: File name too long (36)
> rsync: mknod "/volume1/Backups/syno_app_mover/ContainerManager/extras/@docker/btrfs/subvolumes/14c5239d91670326ca50114d50db43a6182a29022ed13576dd08be66269e5d72/tmp/dotnet-diagnostic-141-389048799-socket" failed: File name too long (36)
> rsync: mknod "/volume1/Backups/syno_app_mover/ContainerManager/extras/@docker/btrfs/subvolumes/14c5239d91670326ca50114d50db43a6182a29022ed13576dd08be66269e5d72/tmp/dotnet-diagnostic-146-100073404-socket" failed: File name too long (36)
> rsync: mknod "/volume1/Backups/syno_app_mover/ContainerManager/extras/@docker/btrfs/subvolumes/14c5239d91670326ca50114d50db43a6182a29022ed13576dd08be66269e5d72/tmp/dotnet-diagnostic-146-62242-socket" failed: File name too long (36)
> rsync: mknod "/volume1/Backups/syno_app_mover/ContainerManager/extras/@docker/btrfs/subvolumes/56b5a0997fe51ed5f2b0bbec2b0b8efcc5295b977db16b4cbf8c25c6906f231e/run/s6-rc:s6-rc-init:mJacKP/servicedirs/s6rc-oneshot-runner/s" failed: File name too long (36)
> rsync: mknod "/volume1/Backups/syno_app_mover/ContainerManager/extras/@docker/btrfs/subvolumes/56b5a0997fe51ed5f2b0bbec2b0b8efcc5295b977db16b4cbf8c25c6906f231e/tmp/dotnet-diagnostic-142-104475015-socket" failed: File name too long (36)
> rsync: mknod "/volume1/Backups/syno_app_mover/ContainerManager/extras/@docker/btrfs/subvolumes/56b5a0997fe51ed5f2b0bbec2b0b8efcc5295b977db16b4cbf8c25c6906f231e/tmp/dotnet-diagnostic-144-389327314-socket" failed: File name too long (36)
> rsync: mknod "/volume1/Backups/syno_app_mover/ContainerManager/extras/@docker/btrfs/subvolumes/b0011ac0f56bc51f6499315260b402e50ce32393723d3c22457e3f0d8b9fb32d/run/s6-rc:s6-rc-init:DhBAKh/servicedirs/s6rc-oneshot-runner/s" failed: File name too long (36)
> rsync: mknod "/volume1/Backups/syno_app_mover/ContainerManager/extras/@docker/btrfs/subvolumes/cccfbeb13ae27620c0e99a10139068b33bd0b360ad46f3f68de61f1228561885/tmp/.org.chromium.Chromium.0dJsP9/SingletonSocket" failed: File name too long (36)
> rsync: mknod "/volume1/Backups/syno_app_mover/ContainerManager/extras/@docker/btrfs/subvolumes/cccfbeb13ae27620c0e99a10139068b33bd0b360ad46f3f68de61f1228561885/tmp/.org.chromium.Chromium.2FC4Ks/SingletonSocket" failed: File name too long (36)
> rsync: mknod "/volume1/Backups/syno_app_mover/ContainerManager/extras/@docker/btrfs/subvolumes/cccfbeb13ae27620c0e99a10139068b33bd0b360ad46f3f68de61f1228561885/tmp/.org.chromium.Chromium.2dS2VC/SingletonSocket" failed: File name too long (36)
> rsync: mknod "/volume1/Backups/syno_app_mover/ContainerManager/extras/@docker/btrfs/subvolumes/cccfbeb13ae27620c0e99a10139068b33bd0b360ad46f3f68de61f1228561885/tmp/.org.chromium.Chromium.3FPurG/SingletonSocket" failed: File name too long (36)
> rsync: mknod "/volume1/Backups/syno_app_mover/ContainerManager/extras/@docker/btrfs/subvolumes/cccfbeb13ae27620c0e99a10139068b33bd0b360ad46f3f68de61f1228561885/tmp/.org.chromium.Chromium.3R7pGd/SingletonSocket" failed: File name too long (36)
> rsync: mknod "/volume1/Backups/syno_app_mover/ContainerManager/extras/@docker/btrfs/subvolumes/cccfbeb13ae27620c0e99a10139068b33bd0b360ad46f3f68de61f1228561885/tmp/.org.chromium.Chromium.3sjXVb/SingletonSocket" failed: File name too long (36)
> rsync: mknod "/volume1/Backups/syno_app_mover/ContainerManager/extras/@docker/btrfs/subvolumes/cccfbeb13ae27620c0e99a10139068b33bd0b360ad46f3f68de61f1228561885/tmp/.org.chromium.Chromium.7TtsRm/SingletonSocket" failed: File name too long (36)
> rsync: mknod "/volume1/Backups/syno_app_mover/ContainerManager/extras/@docker/btrfs/subvolumes/cccfbeb13ae27620c0e99a10139068b33bd0b360ad46f3f68de61f1228561885/tmp/.org.chromium.Chromium.8HQoqI/SingletonSocket" failed: File name too long (36)
> rsync: mknod "/volume1/Backups/syno_app_mover/ContainerManager/extras/@docker/btrfs/subvolumes/cccfbeb13ae27620c0e99a10139068b33bd0b360ad46f3f68de61f1228561885/tmp/.org.chromium.Chromium.8Ns0qZ/SingletonSocket" failed: File name too long (36)
> rsync: mknod "/volume1/Backups/syno_app_mover/ContainerManager/extras/@docker/btrfs/subvolumes/cccfbeb13ae27620c0e99a10139068b33bd0b360ad46f3f68de61f1228561885/tmp/.org.chromium.Chromium.8lsyOt/SingletonSocket" failed: File name too long (36)
> rsync: mknod "/volume1/Backups/syno_app_mover/ContainerManager/extras/@docker/btrfs/subvolumes/cccfbeb13ae27620c0e99a10139068b33bd0b360ad46f3f68de61f1228561885/tmp/.org.chromium.Chromium.9peWAU/SingletonSocket" failed: File name too long (36)
> rsync: mknod "/volume1/Backups/syno_app_mover/ContainerManager/extras/@docker/btrfs/subvolumes/cccfbeb13ae27620c0e99a10139068b33bd0b360ad46f3f68de61f1228561885/tmp/.org.chromium.Chromium.AG3uhl/SingletonSocket" failed: File name too long (36)
> rsync: mknod "/volume1/Backups/syno_app_mover/ContainerManager/extras/@docker/btrfs/subvolumes/cccfbeb13ae27620c0e99a10139068b33bd0b360ad46f3f68de61f1228561885/tmp/.org.chromium.Chromium.BnZ2rN/SingletonSocket" failed: File name too long (36)
> rsync: mknod "/volume1/Backups/syno_app_mover/ContainerManager/extras/@docker/btrfs/subvolumes/cccfbeb13ae27620c0e99a10139068b33bd0b360ad46f3f68de61f1228561885/tmp/.org.chromium.Chromium.CgzSV3/SingletonSocket" failed: File name too long (36)
> rsync: mknod "/volume1/Backups/syno_app_mover/ContainerManager/extras/@docker/btrfs/subvolumes/cccfbeb13ae27620c0e99a10139068b33bd0b360ad46f3f68de61f1228561885/tmp/.org.chromium.Chromium.Ck409y/SingletonSocket" failed: File name too long (36)
> rsync: mknod "/volume1/Backups/syno_app_mover/ContainerManager/extras/@docker/btrfs/subvolumes/cccfbeb13ae27620c0e99a10139068b33bd0b360ad46f3f68de61f1228561885/tmp/.org.chromium.Chromium.Cvj33Q/SingletonSocket" failed: File name too long (36)
> rsync: mknod "/volume1/Backups/syno_app_mover/ContainerManager/extras/@docker/btrfs/subvolumes/cccfbeb13ae27620c0e99a10139068b33bd0b360ad46f3f68de61f1228561885/tmp/.org.chromium.Chromium.D0fgKp/SingletonSocket" failed: File name too long (36)
> rsync: mknod "/volume1/Backups/syno_app_mover/ContainerManager/extras/@docker/btrfs/subvolumes/cccfbeb13ae27620c0e99a10139068b33bd0b360ad46f3f68de61f1228561885/tmp/.org.chromium.Chromium.DTCcNC/SingletonSocket" failed: File name too long (36)
> rsync: mknod "/volume1/Backups/syno_app_mover/ContainerManager/extras/@docker/btrfs/subvolumes/cccfbeb13ae27620c0e99a10139068b33bd0b360ad46f3f68de61f1228561885/tmp/.org.chromium.Chromium.Dhd4KQ/SingletonSocket" failed: File name too long (36)
> rsync: mknod "/volume1/Backups/syno_app_mover/ContainerManager/extras/@docker/btrfs/subvolumes/cccfbeb13ae27620c0e99a10139068b33bd0b360ad46f3f68de61f1228561885/tmp/.org.chromium.Chromium.Dkf8FY/SingletonSocket" failed: File name too long (36)
> rsync: mknod "/volume1/Backups/syno_app_mover/ContainerManager/extras/@docker/btrfs/subvolumes/cccfbeb13ae27620c0e99a10139068b33bd0b360ad46f3f68de61f1228561885/tmp/.org.chromium.Chromium.EZ0Ksm/SingletonSocket" failed: File name too long (36)
> rsync: mknod "/volume1/Backups/syno_app_mover/ContainerManager/extras/@docker/btrfs/subvolumes/cccfbeb13ae27620c0e99a10139068b33bd0b360ad46f3f68de61f1228561885/tmp/.org.chromium.Chromium.JOQCZ7/SingletonSocket" failed: File name too long (36)
> rsync: mknod "/volume1/Backups/syno_app_mover/ContainerManager/extras/@docker/btrfs/subvolumes/cccfbeb13ae27620c0e99a10139068b33bd0b360ad46f3f68de61f1228561885/tmp/.org.chromium.Chromium.Jk2hrE/SingletonSocket" failed: File name too long (36)
> rsync: mknod "/volume1/Backups/syno_app_mover/ContainerManager/extras/@docker/btrfs/subvolumes/cccfbeb13ae27620c0e99a10139068b33bd0b360ad46f3f68de61f1228561885/tmp/.org.chromium.Chromium.KBXI0c/SingletonSocket" failed: File name too long (36)
> rsync: mknod "/volume1/Backups/syno_app_mover/ContainerManager/extras/@docker/btrfs/subvolumes/cccfbeb13ae27620c0e99a10139068b33bd0b360ad46f3f68de61f1228561885/tmp/.org.chromium.Chromium.KIn8AG/SingletonSocket" failed: File name too long (36)
> rsync: mknod "/volume1/Backups/syno_app_mover/ContainerManager/extras/@docker/btrfs/subvolumes/cccfbeb13ae27620c0e99a10139068b33bd0b360ad46f3f68de61f1228561885/tmp/.org.chromium.Chromium.KO2RFn/SingletonSocket" failed: File name too long (36)
> rsync: mknod "/volume1/Backups/syno_app_mover/ContainerManager/extras/@docker/btrfs/subvolumes/cccfbeb13ae27620c0e99a10139068b33bd0b360ad46f3f68de61f1228561885/tmp/.org.chromium.Chromium.NsXp1R/SingletonSocket" failed: File name too long (36)
> rsync: mknod "/volume1/Backups/syno_app_mover/ContainerManager/extras/@docker/btrfs/subvolumes/cccfbeb13ae27620c0e99a10139068b33bd0b360ad46f3f68de61f1228561885/tmp/.org.chromium.Chromium.NuKnhM/SingletonSocket" failed: File name too long (36)
> rsync: mknod "/volume1/Backups/syno_app_mover/ContainerManager/extras/@docker/btrfs/subvolumes/cccfbeb13ae27620c0e99a10139068b33bd0b360ad46f3f68de61f1228561885/tmp/.org.chromium.Chromium.O7ympW/SingletonSocket" failed: File name too long (36)
> rsync: mknod "/volume1/Backups/syno_app_mover/ContainerManager/extras/@docker/btrfs/subvolumes/cccfbeb13ae27620c0e99a10139068b33bd0b360ad46f3f68de61f1228561885/tmp/.org.chromium.Chromium.OHVzz5/SingletonSocket" failed: File name too long (36)
> rsync: mknod "/volume1/Backups/syno_app_mover/ContainerManager/extras/@docker/btrfs/subvolumes/cccfbeb13ae27620c0e99a10139068b33bd0b360ad46f3f68de61f1228561885/tmp/.org.chromium.Chromium.PNFWI1/SingletonSocket" failed: File name too long (36)
> rsync: mknod "/volume1/Backups/syno_app_mover/ContainerManager/extras/@docker/btrfs/subvolumes/cccfbeb13ae27620c0e99a10139068b33bd0b360ad46f3f68de61f1228561885/tmp/.org.chromium.Chromium.Pd4uVd/SingletonSocket" failed: File name too long (36)
> rsync: mknod "/volume1/Backups/syno_app_mover/ContainerManager/extras/@docker/btrfs/subvolumes/cccfbeb13ae27620c0e99a10139068b33bd0b360ad46f3f68de61f1228561885/tmp/.org.chromium.Chromium.PzSKuY/SingletonSocket" failed: File name too long (36)
> rsync: mknod "/volume1/Backups/syno_app_mover/ContainerManager/extras/@docker/btrfs/subvolumes/cccfbeb13ae27620c0e99a10139068b33bd0b360ad46f3f68de61f1228561885/tmp/.org.chromium.Chromium.Q3kw74/SingletonSocket" failed: File name too long (36)
> rsync: mknod "/volume1/Backups/syno_app_mover/ContainerManager/extras/@docker/btrfs/subvolumes/cccfbeb13ae27620c0e99a10139068b33bd0b360ad46f3f68de61f1228561885/tmp/.org.chromium.Chromium.SyUS9g/SingletonSocket" failed: File name too long (36)
> rsync: mknod "/volume1/Backups/syno_app_mover/ContainerManager/extras/@docker/btrfs/subvolumes/cccfbeb13ae27620c0e99a10139068b33bd0b360ad46f3f68de61f1228561885/tmp/.org.chromium.Chromium.U3PVqZ/SingletonSocket" failed: File name too long (36)
> rsync: mknod "/volume1/Backups/syno_app_mover/ContainerManager/extras/@docker/btrfs/subvolumes/cccfbeb13ae27620c0e99a10139068b33bd0b360ad46f3f68de61f1228561885/tmp/.org.chromium.Chromium.UqUgX9/SingletonSocket" failed: File name too long (36)
> rsync: mknod "/volume1/Backups/syno_app_mover/ContainerManager/extras/@docker/btrfs/subvolumes/cccfbeb13ae27620c0e99a10139068b33bd0b360ad46f3f68de61f1228561885/tmp/.org.chromium.Chromium.VjBGW0/SingletonSocket" failed: File name too long (36)
> rsync: mknod "/volume1/Backups/syno_app_mover/ContainerManager/extras/@docker/btrfs/subvolumes/cccfbeb13ae27620c0e99a10139068b33bd0b360ad46f3f68de61f1228561885/tmp/.org.chromium.Chromium.VooR82/SingletonSocket" failed: File name too long (36)
> rsync: mknod "/volume1/Backups/syno_app_mover/ContainerManager/extras/@docker/btrfs/subvolumes/cccfbeb13ae27620c0e99a10139068b33bd0b360ad46f3f68de61f1228561885/tmp/.org.chromium.Chromium.VuxQxb/SingletonSocket" failed: File name too long (36)
> rsync: mknod "/volume1/Backups/syno_app_mover/ContainerManager/extras/@docker/btrfs/subvolumes/cccfbeb13ae27620c0e99a10139068b33bd0b360ad46f3f68de61f1228561885/tmp/.org.chromium.Chromium.W9NZkR/SingletonSocket" failed: File name too long (36)
> rsync: mknod "/volume1/Backups/syno_app_mover/ContainerManager/extras/@docker/btrfs/subvolumes/cccfbeb13ae27620c0e99a10139068b33bd0b360ad46f3f68de61f1228561885/tmp/.org.chromium.Chromium.XxFUpS/SingletonSocket" failed: File name too long (36)
> rsync: mknod "/volume1/Backups/syno_app_mover/ContainerManager/extras/@docker/btrfs/subvolumes/cccfbeb13ae27620c0e99a10139068b33bd0b360ad46f3f68de61f1228561885/tmp/.org.chromium.Chromium.ZFSQrs/SingletonSocket" failed: File name too long (36)
> rsync: mknod "/volume1/Backups/syno_app_mover/ContainerManager/extras/@docker/btrfs/subvolumes/cccfbeb13ae27620c0e99a10139068b33bd0b360ad46f3f68de61f1228561885/tmp/.org.chromium.Chromium.cZxKeb/SingletonSocket" failed: File name too long (36)
> rsync: mknod "/volume1/Backups/syno_app_mover/ContainerManager/extras/@docker/btrfs/subvolumes/cccfbeb13ae27620c0e99a10139068b33bd0b360ad46f3f68de61f1228561885/tmp/.org.chromium.Chromium.dNCJhO/SingletonSocket" failed: File name too long (36)
> rsync: mknod "/volume1/Backups/syno_app_mover/ContainerManager/extras/@docker/btrfs/subvolumes/cccfbeb13ae27620c0e99a10139068b33bd0b360ad46f3f68de61f1228561885/tmp/.org.chromium.Chromium.dvAn5f/SingletonSocket" failed: File name too long (36)
> rsync: mknod "/volume1/Backups/syno_app_mover/ContainerManager/extras/@docker/btrfs/subvolumes/cccfbeb13ae27620c0e99a10139068b33bd0b360ad46f3f68de61f1228561885/tmp/.org.chromium.Chromium.fMIojZ/SingletonSocket" failed: File name too long (36)
> rsync: mknod "/volume1/Backups/syno_app_mover/ContainerManager/extras/@docker/btrfs/subvolumes/cccfbeb13ae27620c0e99a10139068b33bd0b360ad46f3f68de61f1228561885/tmp/.org.chromium.Chromium.gGJksH/SingletonSocket" failed: File name too long (36)
> rsync: mknod "/volume1/Backups/syno_app_mover/ContainerManager/extras/@docker/btrfs/subvolumes/cccfbeb13ae27620c0e99a10139068b33bd0b360ad46f3f68de61f1228561885/tmp/.org.chromium.Chromium.gdBkbP/SingletonSocket" failed: File name too long (36)
> rsync: mknod "/volume1/Backups/syno_app_mover/ContainerManager/extras/@docker/btrfs/subvolumes/cccfbeb13ae27620c0e99a10139068b33bd0b360ad46f3f68de61f1228561885/tmp/.org.chromium.Chromium.k9fjkK/SingletonSocket" failed: File name too long (36)
> rsync: mknod "/volume1/Backups/syno_app_mover/ContainerManager/extras/@docker/btrfs/subvolumes/cccfbeb13ae27620c0e99a10139068b33bd0b360ad46f3f68de61f1228561885/tmp/.org.chromium.Chromium.l8Sbzk/SingletonSocket" failed: File name too long (36)
> rsync: mknod "/volume1/Backups/syno_app_mover/ContainerManager/extras/@docker/btrfs/subvolumes/cccfbeb13ae27620c0e99a10139068b33bd0b360ad46f3f68de61f1228561885/tmp/.org.chromium.Chromium.mBDV8a/SingletonSocket" failed: File name too long (36)
> rsync: mknod "/volume1/Backups/syno_app_mover/ContainerManager/extras/@docker/btrfs/subvolumes/cccfbeb13ae27620c0e99a10139068b33bd0b360ad46f3f68de61f1228561885/tmp/.org.chromium.Chromium.mGzBUY/SingletonSocket" failed: File name too long (36)
> rsync: mknod "/volume1/Backups/syno_app_mover/ContainerManager/extras/@docker/btrfs/subvolumes/cccfbeb13ae27620c0e99a10139068b33bd0b360ad46f3f68de61f1228561885/tmp/.org.chromium.Chromium.njAu6s/SingletonSocket" failed: File name too long (36)
> rsync: mknod "/volume1/Backups/syno_app_mover/ContainerManager/extras/@docker/btrfs/subvolumes/cccfbeb13ae27620c0e99a10139068b33bd0b360ad46f3f68de61f1228561885/tmp/.org.chromium.Chromium.nkvaRJ/SingletonSocket" failed: File name too long (36)
> rsync: mknod "/volume1/Backups/syno_app_mover/ContainerManager/extras/@docker/btrfs/subvolumes/cccfbeb13ae27620c0e99a10139068b33bd0b360ad46f3f68de61f1228561885/tmp/.org.chromium.Chromium.o1aG3B/SingletonSocket" failed: File name too long (36)
> rsync: mknod "/volume1/Backups/syno_app_mover/ContainerManager/extras/@docker/btrfs/subvolumes/cccfbeb13ae27620c0e99a10139068b33bd0b360ad46f3f68de61f1228561885/tmp/.org.chromium.Chromium.oJZdp0/SingletonSocket" failed: File name too long (36)
> rsync: mknod "/volume1/Backups/syno_app_mover/ContainerManager/extras/@docker/btrfs/subvolumes/cccfbeb13ae27620c0e99a10139068b33bd0b360ad46f3f68de61f1228561885/tmp/.org.chromium.Chromium.pvggQa/SingletonSocket" failed: File name too long (36)
> rsync: mknod "/volume1/Backups/syno_app_mover/ContainerManager/extras/@docker/btrfs/subvolumes/cccfbeb13ae27620c0e99a10139068b33bd0b360ad46f3f68de61f1228561885/tmp/.org.chromium.Chromium.qGQss9/SingletonSocket" failed: File name too long (36)
> rsync: mknod "/volume1/Backups/syno_app_mover/ContainerManager/extras/@docker/btrfs/subvolumes/cccfbeb13ae27620c0e99a10139068b33bd0b360ad46f3f68de61f1228561885/tmp/.org.chromium.Chromium.rLNwGW/SingletonSocket" failed: File name too long (36)
> rsync: mknod "/volume1/Backups/syno_app_mover/ContainerManager/extras/@docker/btrfs/subvolumes/cccfbeb13ae27620c0e99a10139068b33bd0b360ad46f3f68de61f1228561885/tmp/.org.chromium.Chromium.rTvoGb/SingletonSocket" failed: File name too long (36)
> rsync: mknod "/volume1/Backups/syno_app_mover/ContainerManager/extras/@docker/btrfs/subvolumes/cccfbeb13ae27620c0e99a10139068b33bd0b360ad46f3f68de61f1228561885/tmp/.org.chromium.Chromium.rpro9u/SingletonSocket" failed: File name too long (36)
> rsync: mknod "/volume1/Backups/syno_app_mover/ContainerManager/extras/@docker/btrfs/subvolumes/cccfbeb13ae27620c0e99a10139068b33bd0b360ad46f3f68de61f1228561885/tmp/.org.chromium.Chromium.sPUQpW/SingletonSocket" failed: File name too long (36)
> rsync: mknod "/volume1/Backups/syno_app_mover/ContainerManager/extras/@docker/btrfs/subvolumes/cccfbeb13ae27620c0e99a10139068b33bd0b360ad46f3f68de61f1228561885/tmp/.org.chromium.Chromium.v0Gndp/SingletonSocket" failed: File name too long (36)
> rsync: mknod "/volume1/Backups/syno_app_mover/ContainerManager/extras/@docker/btrfs/subvolumes/cccfbeb13ae27620c0e99a10139068b33bd0b360ad46f3f68de61f1228561885/tmp/.org.chromium.Chromium.v0iuAX/SingletonSocket" failed: File name too long (36)
> rsync: mknod "/volume1/Backups/syno_app_mover/ContainerManager/extras/@docker/btrfs/subvolumes/cccfbeb13ae27620c0e99a10139068b33bd0b360ad46f3f68de61f1228561885/tmp/.org.chromium.Chromium.vbWnZd/SingletonSocket" failed: File name too long (36)
> rsync: mknod "/volume1/Backups/syno_app_mover/ContainerManager/extras/@docker/btrfs/subvolumes/cccfbeb13ae27620c0e99a10139068b33bd0b360ad46f3f68de61f1228561885/tmp/.org.chromium.Chromium.wTUq1o/SingletonSocket" failed: File name too long (36)
> rsync: mknod "/volume1/Backups/syno_app_mover/ContainerManager/extras/@docker/btrfs/subvolumes/cccfbeb13ae27620c0e99a10139068b33bd0b360ad46f3f68de61f1228561885/tmp/.org.chromium.Chromium.ychKpr/SingletonSocket" failed: File name too long (36)
> rsync: mknod "/volume1/Backups/syno_app_mover/ContainerManager/extras/@docker/btrfs/subvolumes/cccfbeb13ae27620c0e99a10139068b33bd0b360ad46f3f68de61f1228561885/tmp/.org.chromium.Chromium.yeUMJo/SingletonSocket" failed: File name too long (36)
> rsync: mknod "/volume1/Backups/syno_app_mover/ContainerManager/extras/@docker/btrfs/subvolumes/cccfbeb13ae27620c0e99a10139068b33bd0b360ad46f3f68de61f1228561885/tmp/.org.chromium.Chromium.ylZ64W/SingletonSocket" failed: File name too long (36)
> rsync: mknod "/volume1/Backups/syno_app_mover/ContainerManager/extras/@docker/btrfs/subvolumes/cccfbeb13ae27620c0e99a10139068b33bd0b360ad46f3f68de61f1228561885/tmp/.org.chromium.Chromium.zH3obA/SingletonSocket" failed: File name too long (36)
> rsync: mknod "/volume1/Backups/syno_app_mover/ContainerManager/extras/@docker/btrfs/subvolumes/cccfbeb13ae27620c0e99a10139068b33bd0b360ad46f3f68de61f1228561885/tmp/.org.chromium.Chromium.zeZ6Un/SingletonSocket" failed: File name too long (36)
> rsync: mknod "/volume1/Backups/syno_app_mover/ContainerManager/extras/@docker/btrfs/subvolumes/cccfbeb13ae27620c0e99a10139068b33bd0b360ad46f3f68de61f1228561885/tmp/.org.chromium.Chromium.zuTEZX/SingletonSocket" failed: File name too long (36)
> rsync: mknod "/volume1/Backups/syno_app_mover/ContainerManager/extras/@docker/btrfs/subvolumes/f2d2b0a8b3869840a23b7b7106df8b3c751f8c5acc02983ea07478c677ef6858/run/s6-rc:s6-rc-init:Paoich/servicedirs/s6rc-oneshot-runner/s" failed: File name too long (36)
> rsync: mknod "/volume1/Backups/syno_app_mover/ContainerManager/extras/@docker/btrfs/subvolumes/f2d2b0a8b3869840a23b7b7106df8b3c751f8c5acc02983ea07478c677ef6858/tmp/dotnet-diagnostic-145-389364028-socket" failed: File name too long (36)
> rsync: mknod "/volume1/Backups/syno_app_mover/ContainerManager/extras/@docker/btrfs/subvolumes/f2d2b0a8b3869840a23b7b7106df8b3c751f8c5acc02983ea07478c677ef6858/tmp/dotnet-diagnostic-145-43491306-socket" failed: File name too long (36)
> rsync: mknod "/volume1/Backups/syno_app_mover/ContainerManager/extras/@docker/btrfs/subvolumes/f2d2b0a8b3869840a23b7b7106df8b3c751f8c5acc02983ea07478c677ef6858/tmp/dotnet-diagnostic-145-43553574-socket" failed: File name too long (36)
> rsync: mknod "/volume1/Backups/syno_app_mover/ContainerManager/extras/@docker/btrfs/subvolumes/f2d2b0a8b3869840a23b7b7106df8b3c751f8c5acc02983ea07478c677ef6858/tmp/dotnet-diagnostic-146-27632-socket" failed: File name too long (36)
> rsync: mknod "/volume1/Backups/syno_app_mover/ContainerManager/extras/@docker/btrfs/subvolumes/f2d2b0a8b3869840a23b7b7106df8b3c751f8c5acc02983ea07478c677ef6858/tmp/dotnet-diagnostic-146-6273973-socket" failed: File name too long (36)
> rsync: mknod "/volume1/Backups/syno_app_mover/ContainerManager/extras/@docker/btrfs/subvolumes/f2d2b0a8b3869840a23b7b7106df8b3c751f8c5acc02983ea07478c677ef6858/tmp/dotnet-diagnostic-150-43479259-socket" failed: File name too long (36)
> rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1464) [sender=3.1.2]
> Line 577: ERROR Backing up /volume1/@docker failed!
> progstatus called from copy_dir line 1146
> 
> Finished backing up Container Manager
> 
> Duration: 1h 46m

**Comment by 007revad** [comment]
Is volume 1, or Backups shared folder, encrypted?

**Comment by stevenhaskell** [comment]
@007revad no, neither are encrypted.

**Comment by 007revad** [comment]
All of those folders rsync is trying to create are 185 to 208 characters long.

Someone else had the same "rsync: mknod failed: File name too long (36)" error with much shorter folder paths. They determined that the error message was misleading. https://serverfault.com/questions/1122911/rsync-generator-mknod-failed-file-name-too-long-36-though-file-path 

I wish we knew which containers those 6 causing errors are. 

They are all also s6rc-oneshot-runner or socket from tmp or run folders. I could make rysnc exclude tmp folders, but I'm not sure about the run folder.

**Comment by 007revad** [comment]
Okay. Both run and tmp are volatile folders.

I think excluding tmp and run from the backup would work because you'd need to have the container installed before restoring a backup, and installing the container would create the run and tmp folders and their contents when the container starts.

**Comment by 007revad** [comment]
Do you want to try [v4.0.66](https://github.com/007revad/Synology_app_mover/releases/tag/v4.0.66)

- Bug fix for "rsync: mknod failed: File name too long (36)" when backing up `@docker`. Issue #120

**Comment by 007revad** [comment]
PS Thanks for the coffee.

**Comment by stevenhaskell** [comment]
@007revad It worked! No errors and it cut the backup time down to 53m from 1h 46m.

Thanks again for your help!
