### ISSUE TITLE
Is it possible to extract an app and containerize it?

### ISSUE THREAD

**Issue by lenaxia** [007revad/Synology_app_mover#137]
Specific use case is pulling Syno photos out and running it on a separate server with folders mapped back to the Syno. I'd also be interested in providing an external postgres as I am running one in k3s with automatic backups. 

I want to do this to provide more compute power behind photos.

**Comment by 007revad** [comment]
Unfortunately I don't have experience in containerizing an app.

Modifying Synology Photos to use an external postgres database would require reverse engineering. And I suspect Synology's lawyers might not be to impressed if I started reverse engineering Synology Photos.

You can extract the [Synology Photos spk](https://archive.synology.com/download/Package/SynologyPhotos) file with https://github.com/007revad/Synology_Archive_Extractor if you want to have a look at the package.
