### ISSUE TITLE
error in package list retrieval

### ISSUE THREAD

**Issue by phit42** [007revad/Synology_app_mover#138]
I ran the current version for the first time in order to backup some packages. Unfortunately it ran right into an error when trying to retrieve the installed packages. It then shows me only two packages, of which the first one is labelled "/volume1".

`root@myds:/volume1/download/Synology_app_mover/Synology_app_mover-4.2.75# ./syno_app_mover.sh
Synology_app_mover v4.2.75
DS415+-j DSM 7.1.1-42962-6

Running from: /volume1/download/Synology_app_mover/Synology_app_mover-4.2.75/syno_app_mover.sh

1) Move
2) Backup
3) Restore
Select the mode: 2
You selected Backup

Backup path is: /volumeUSB1/usbshare/

**./syno_app_mover.sh: line 2039: package_names["${package_name}"]: bad array subscript**
Do you want to backup All packages? [y/n]
n
[Installed package list]
1) /volume1
`

Also, it is telling me that there are 0 GB free on an externally connected USB drive with roughly 1TB free space?

**Comment by 007revad** [comment]
If you go to "Package Center > Installed" are any packages showing as broken or need repair?

Check if any packages are missing their INFO file:
```
for p in /var/packages/*; do if [[ ! -f $p/INFO ]]; then echo "Missing INFO: $p"; fi; done
```

**Comment by 007revad** [comment]
What do these commands return?
```
df | grep "/volumeUSB1/usbshare" | awk '{print $4}'
df | grep "/volumeUSB1/usbshare"
```

**Comment by phit42** [comment]
Sorry for the late reply. No installed package shows as broken or in need of repair, one package seems to be missing its info though:
`root@myds:/volume1/download/Synology_app_mover/Synology_app_mover-4.2.75# for p in /var/packages/*; do if [[ ! -f $p/INFO ]]; then echo "Missing INFO: $p"; fi; done`
`Missing INFO: /var/packages/ebi`

And here is the other output that you requested:
`root@myds:/volume1/download/Synology_app_mover/Synology_app_mover-4.2.75# df | grep "/volumeUSB1/usbshare"$ | awk '{print $4}'`
`2991280116`
`root@myds:/volume1/download/Synology_app_mover/Synology_app_mover-4.2.75# df | grep "/volumeUSB1/usbshare"$`
`/dev/sdq1              11625427352  8634060788 2991247780  75% /volumeUSB1/usbshare`
`root@myds:/volume1/download/Synology_app_mover/Synology_app_mover-4.2.75# df --output=avail "/volumeUSB1/usbshare" | grep -A1 Avail | grep -v Avail`
`2991247780`

**Comment by 007revad** [comment]
How did you get Easy Bootstrap Installer installed in DSM 7.1.1? Did you install it in DSM 6 and then later update to DSM 7?

As far as I know QTip was unable to update Easy Bootstrap Installer to install in DSM 7. 

It still shows up in DSM 7.2.2 in package center if you add cphub.net as a package source. But when I click on install nothing happens. So I checked the cphub.net website and there's a link to it on the side bar under "top apps" but the link gives a 500 error. https://www.cphub.net/?p=ebi

I suspect you have an empty /var/packages/ebi folder left over from when you had Easy Bootstrap Installer installed.

I'll change the script to skip apps that don't have an INFO file.

I'm still looking into the USB drive free space issue.

**Comment by 007revad** [comment]
Fixed in https://github.com/007revad/Synology_app_mover/releases/tag/v4.2.77

- Bug fix for 'bad array subscript' when app is missing it's INFO file. Issue #138
- Bug fix for checking free space on USB drives. Issue #138

**Comment by 007revad** [comment]
That should have been https://github.com/007revad/Synology_app_mover/releases/tag/v4.2.78

**Comment by phit42** [comment]
> How did you get Easy Bootstrap Installer installed in DSM 7.1.1? Did you install it in DSM 6 and then later update to DSM 7?
> 
> As far as I know QTip was unable to update Easy Bootstrap Installer to install in DSM 7.
> 
> It still shows up in DSM 7.2.2 in package center if you add cphub.net as a package source. But when I click on install nothing happens. So I checked the cphub.net website and there's a link to it on the side bar under "top apps" but the link gives a 500 error. https://www.cphub.net/?p=ebi
> 
> I suspect you have an empty /var/packages/ebi folder left over from when you had Easy Bootstrap Installer installed.
> 
> I'll change the script to skip apps that don't have an INFO file.
> 
> I'm still looking into the USB drive free space issue.

Hi @007revad , yes I had EBI installed at one point before DSM 7 I think, but it is not installed anymore. I guess the uninstall left the directory dangling. Thank you for the fix! I also removed the dir now. 
PS Wouldn't it be safer to double-check installation status via synopkg or sth? EBI wasn't listed there.

Anyway it works now and also seems to check usb space correctly, so thanx again.
