### ISSUE TITLE
Docker error need urgent help

### ISSUE THREAD

**Issue by BlackJoker90** [007revad/Synology_app_mover#139]
I recently moved the Container Manager from Volume1 to Volume2, following the official instructions step by step. However, I am now experiencing several critical issues. While I managed to update the paths for some containers and successfully started them (as shown in the attached screenshot), many other containers are failing to start or adjust.

One of the most critical containers, Paperless-NGX, refuses to start, and I am encountering various error messages for different containers. When I try to deploy the stack in portainer nothing happens. In the Container Manager in DSM the Log says the Container is marked to removal and cannot be startet. 

![image](https://github.com/user-attachments/assets/f650f3eb-4075-4d4a-87b0-d3f12e8d2d0a)

**Comment by 007revad** [comment]
That's a LOT of broken containers. Were there any errors from the script when you ran it?

Are both volume1 and volume2 btrfs? Or both ext4?

The orphaned containers script ( https://github.com/007revad/Synology_docker_cleanup ) should remove the broken containers and images. But make sure you have a backup of all your docker compose files - just in case something that is currently working gets removed. If I remember correctly you should have all the working containers running so their images don't get deleted.

**Comment by BlackJoker90** [comment]
No errors occurred in the script; everything ran smoothly. After hours of work, I restored a Hyper Backup of my Docker folder, reinstalled the Container Manager on Volume1, and recreated all containers.  

However, two issues remain:  

1. I cannot delete the @docker folder on Volume2, even with sudo via SSH.  
2. I attempted to move only my Paperless NGX instance to the SSD, but the Redis broker failed to start.  

Can we resolve these two issues?

**Comment by BlackJoker90** [comment]
I was able to solve the first problem with the folder after I unmounted the docker volumes but I would be very happy to solve the paperless ngx redis problem

**Comment by 007revad** [comment]
I didn't even know what Paperless NGX or redis were until a minute ago.

Does your Paperless NGX docker compose look anything like these: https://github.com/paperless-ngx/paperless-ngx/tree/main/docker/compose

**Comment by BlackJoker90** [comment]
I was able to solve the problem:
https://github.com/paperless-ngx/paperless-ngx/discussions/8400#discussioncomment-11430680
