### ISSUE TITLE
Backup errors starting/stopping container manager

### ISSUE THREAD

**Issue by enieuwy** [007revad/Synology_app_mover#140]
I've tried to backup Container Manager (only). Reports size as 276GB. Containers are successfully exported, but then I receive the error:
```
Removing dangling docker images
Line 569: ERROR Stopping Container Manager failed!
progstatus called from package_stop line 647 (v4.2.75)
```
In the Synology GUI, the container manager package hung at "stopping".
After rebooting the NAS, container manager was stopped so I tried the backup task again. This time it failed to start:
```
Ready to Backup Container Manager to /volume1/backups? [y/n]
y

Line 569: ERROR Starting Container Manager failed!
progstatus called from package_start line 670 (v4.2.75)
```
Perhaps it just didn't wait long enough, because container manager successfully started after this error.

**Comment by 007revad** [comment]
The script has a 5 minute timeout when stopping and starting packages. I added the timeout in case a package hangs so it won't prevent other packages from being backup or restored if "all" packages were selected.

I could change it to only use the timeout if more than 1 package is selected.

I'm curious how long Container Manager takes to start for you. Can you stop Container Manager then start it and time how long it takes?

**Comment by enieuwy** [comment]
I have about 71 containers. System resources aren't being taxed during the start/stop (much headroom remains). Watching the logs shows each container is stopped sequentially, taking 3-10 seconds each.

In total, it took 11m35s to stop Container Manager via the UI.

**Comment by enieuwy** [comment]
Restarting from the UI took 14m45s

**Comment by 007revad** [comment]
That's a lot longer than I expected. 

Do you want to try this new version.
https://github.com/007revad/Synology_app_mover/releases/tag/v4.2.76

**Comment by 007revad** [comment]
According to my math
- Stopping 71 containers took an avg of 9.79 seconds each.
- Starting 71 containers took an avg 12.46 seconds each.

I could get the number of containers and multiply it 15 seconds then warn the user how many minutes starting or stopping could take.

Then set the timeout to that number plus 5 minutes.

**Comment by 007revad** [comment]
Fixed in https://github.com/007revad/Synology_app_mover/releases/tag/v4.2.77

- Changed timeout for starting and stopping apps from 5 minutes to 30 minutes. Issue #140
  - Container Manager with lots of containers takes longer than 5 minutes to stop or start.
- Changed to only use the timeout when there is more than 1 app to backup or restore. Issue #140

**Comment by albertusQuelle** [comment]
I have the same problem, jusing v4.2.80

![image](https://github.com/user-attachments/assets/6053512a-5551-46a5-806f-ad171952a37d)

**Comment by 007revad** [comment]
Do you have container manager installed?

**Comment by albertusQuelle** [comment]
Ups, that was my fault, just installed it and will run the script again :)

**Comment by 007revad** [comment]
That's okay. You just highlighted that I need to update the script to check if app being restored is already installed.

**Comment by albertusQuelle** [comment]
Cool, you see in every feedback an opportunity to harden and strengthen your codes

**Comment by 007revad** [comment]
I just checked and it already checks if the package is installed. But for some reason it didn't work for you.

Which DSM version are you using?

If you haven't installed container manager yet, what does the following command return?
```
sudo synopkg status ContainerManager && echo $?
```

**Comment by albertusQuelle** [comment]
```
{"aspect":{"active":{"status":"running","status_code":0,"status_description":"retrieve from status script"}},"description":"Status: [0], package is started","package":"ContainerManager","status":"running"}
0

```
