### ISSUE TITLE
Restore apps after fresh install DSM

### ISSUE THREAD

**Issue by crisfd** [007revad/Synology_app_mover#148]
Hello. I want to reinstall DSM and I have an app that is no longer available as spk file to be able to reinstall (qBittorrent v4.5.5 Web UI (64-bit) for DSM 6.2.4). Is it possible to restore a backup of the app after fresh install of DSM? I've tried that but DSM is not showing the app. I know that I can use docker to install but I rather not. Thanks.

**Comment by 007revad** [comment]
Unfortunately no. Restoring an app backup from DSM 6 in DSM 7 would have a number of issues.

Where did you get the qBittorrent v4.5.5 Web UI (64-bit) for DSM 6.2.4 spk file from?

**Comment by crisfd** [comment]
Well I installed from spk6.imnks.com but it is no longer available. To the best of my knowledge it is the latest version available for dsm6 and better than download station or transmission or deluge. Thank you.
