### ISSUE TITLE
Container manager can't remove containers after move

### ISSUE THREAD

**Issue by rdebeuze** [007revad/Synology_app_mover#149]
I have been up and running for several weeks now since moving all my applications to another volume. The application is really great! 

However, I am now running into a small problem. If you update a container, it brings a new one live with a new version, but the old one cannot be deleted, for example p1mon-p1monitor-1.syno.bak. I get an error in the gui. 

Now I thought if I forcefully do this via SSH, this will probably be possible, but that doesn't work either, I get this error:
Error response from daemon: container 19df01bf0dfe563f57c55ee307a1cfc2c821decd13bcbbc4c327a9315fca1d9f: driver "btrfs" failed to remove root filesystem: Failed to destroy btrfs snapshot /volume2/@docker/btrfs/subvolumes for a808f66aff44cf771e0e147a3b62cafb6e6017ffa5847bce6127d041e25400f8: invalid argument

Is that a known thing?

**Comment by 007revad** [comment]
Try https://github.com/007revad/Synology_docker_cleanup

**Comment by rdebeuze** [comment]
Thankyou that works fine!
