### ISSUE TITLE
@database not move

### ISSUE THREAD

**Issue by met989** [007revad/Synology_app_mover#151]
I try to move the @database from volume2 to volume3 but it gives me an error

`Synology_app_mover v4.2.78
DS411jv10-j DSM 6.2.4-25556-8

Running from: /volume3/temporaneo/mover/syno_app_mover.sh

1) Move
2) Backup
3) Restore
Select the mode: 1
You selected Move

[Installed package list]
1) /volume2  @database           3) /volume3  Hyper Backup Vault
2) /volume3  Hyper Backup        4) /volume3  Log Center
Select the package to move: 1
You selected @database in /volume2

1) /volume1
2) /volume3
Select the destination volume: 3
Invalid choice!
Select the destination volume: 2
You selected /volume3

Checking size of @database
Size of selected app(s) is 40 MB

Ready to Move @database to /volume3? [y/n]
y

/volume3/temporaneo/mover/syno_app_mover.sh: line 2863: systemctl: command not found
Line 574: ERROR Stopping pgsql service and dependent apps failed!
progstatus called from move_database line 2869 (v4.2.78)
`

**Comment by 007revad** [comment]
Replied in https://github.com/007revad/Synology_app_mover/issues/150
