### ISSUE TITLE
Failed to move MailPlus Server to another volume

### ISSUE THREAD

**Issue by meigetsu** [007revad/Synology_app_mover#20]
Hello @007revad,

First of all, I discovered your script a few days ago and I am so glad you did it !
Having an hard drive issue on my main volume 1 (with HDD), I wanted to migrate everything to my completely new SSD Volume (DSM refusing me to mix HDD and SSD which would have been a smoother transition...).
It's also completely crazy that Synology offers no simple way to migrate everything to another volume in purpose of removing the old volume...

Anyways, I used your script to move all my installed applications (around 20) without losing any data.
Unfortunately, I had issues with two migrations using the latest available version at the time : 2.0.6.

First of all, docker migration had issues removing some data in @docker/btrfs folder at the end of the migration. Not so much of an issue but there seems to be a attributes/flag problem on th efolders. I cannot remove them manually either.
Container manager seemed to behave correctly for most existing containers except when I started to remove/recreate some of them. Then it started to fail, refusing me to delete them fort strange reasons (btrfs driver issue ?). Maybe linked to the folders not removed properly ?
I also had an issue with a projetc/container created through WebStation and that was referencing the old volume1 and refusing to startup. Unfortunately, this reference to volume 1 was hidden somewhere and I couldn't find where (neither in compose.yml nor each containers configuration).
Finally it was not such an issue to me because I wanted to redo everything properly anyways so that's ok. But so you know that there is still some isuues there

But the biggest issue to me here is migrating MailPlus Server, I had quite a peek of adrenaline while migrating it ! 😄
Migration wen't well, without any issue in the script execution but. I already had moved the MailPlus shared folder to the new volume  before running your script to migrate the sever (it may be important?).
Unfortunatly, when the MailPlusServer restarted, it seemd to hve restarted from a fresh installation. I couldn't connect anymore to my previously configured accounts. When oening the administration tool, it invited me to create my first account as if it was freshly installed.
At that moment, I juste praided that moving the app back to volume 1 would fix it and it was the case ! So everything is ok as for now. But I am still stuck with that last app on volume 1.

I am also deeply linked to the directory server for my accounts, and especially for MailPlus Server, maybe this has something to do with it ? It seems like if there was a folder/config missing when moving from one volume to another.

Hope you can manage to identify the problem, it would really help ! 😃

**Comment by 007revad** [comment]
I'm actually looking at Container Manager right now. The next version of the script will include backup and restore modes and while testing the restore mode Container Manager I'm getting an error that `/volume1/@appdata/ContainerManager'` is not empty. I also can't delete the `/volume1/@appdata/ContainerManager'` folder via SSH, but I can delete it in WinSCP. I've had the same issue with removing some data in `@docker/btrfs` folder.

The files in `/volume1/@appdata/ContainerManager'` seem to not get moved when moving Container Manager so it appears there's some docker process still running when I stop the Container Manager package and this process has locked the files.

I'll have a look at Web Station.

I originally had the same "create your first account" issue after moving MailPlusServer but thought I'd solved it. Maybe there's something extra I need to do if directory server is installed.

**Comment by holocronology** [comment]
> an error that `/volume1/@appdata/ContainerManager'` is not empty

Appears to be occuring during a move operation as well:
![image](https://github.com/007revad/Synology_app_mover/assets/65265114/38fc2e25-3270-4bd9-a2d5-26ee00d77961)

**Comment by 007revad** [comment]
@meigetsu 

Sorry, I forgot about this issue. I've spent 7 hours today searching for the cause but I've finally found what was missing. I'll have a new version on GitHub shortly.

**Comment by 007revad** [comment]
Moving MailPlus Server is now working. https://github.com/007revad/Synology_app_mover/releases/tag/v3.0.41

**Comment by meigetsu** [comment]
> @meigetsu
> 
> Sorry, I forgot about this issue. I've spent 7 hours today searching for the cause but I've finally found what was missing. I'll have a new version on GitHub shortly.

No worries! Thank you for the patch, I'll give it a try as soon as possible !
