### ISSUE TITLE
v2.0.6 Script Error

### ISSUE THREAD

**Issue by mrxxxxxx** [007revad/Synology_app_mover#21]
Hello,

on my DS918+ with DSM 7.2.1-69057 Update 3, i start the script syno_app_mover.sh  v2.0.6 and short time after there follows this error.

syno_app_mover.sh: line 507: syntax error near unexpected token `<'
syno_app_mover.sh: line 507: `    done < <(find . -maxdepth 2 -type l -ls | grep "$1"'$' | awk '{print $(NF-2), $NF}')'

thanx for Help and for this great Tool -- if it run's :-)

**Comment by 007revad** [comment]
Did you download the .zip file from here: https://github.com/007revad/Synology_app_mover/releases/tag/v2.0.6 and save it to a shared folder on the Synology?

Then unzip the downloaded zip file and run the script from that folder?

**Comment by mrxxxxxx** [comment]
Hello Dave,

yes download from git, then i put it into a Sharefolder on my DS918+, then unzip there. Per ssh on my DS918 change to the unzip folder from syno_app_mover.sh then i run the script syno_app_mover.sh with command
      sh syno_app_mover.sh
the error follows.

same error with 
      sudo sh syno_app_mover.sh
and same as with user root

thanx for help

**Comment by 007revad** [comment]
Try `sudo -s ./syno_app_mover.sh`

**Comment by mrxxxxxx** [comment]
Looks good. The mistake is gone. Soon I will use the script and am curious to see if it does what it should. Great. 

 Thank you very much
