### ISSUE TITLE
v3.0 Beta test results - container manager

### ISSUE THREAD

**Issue by wallacebrf** [007revad/Synology_app_mover#22]
Synology_app_mover v3.0.15
DS920+ DSM 7.2.1-69057-4

Backup took a long time even with just a simple installation of containers. This is not the faulkt of the script

However, I would suggest, before the line 
`"Backing up /volumexyz/@docker/ContainerManager." `
add a warning maybe in red text that this will take a very long time. 

Just a couple of containers took 12 minutes to backup. i can see other people's installations taking hours, especially if they are using PLEX and other large containers.

**Comment by 007revad** [comment]
How large is your `@docker` folder?

Which containers did you have installed?

**Comment by wallacebrf** [comment]
it is 29GB

ldap-agent
watchtower
chromium
synology_docviewer_2
synology_docviewer_1


an interesting question just popped into my head. ldap agent, and the synology_docviewer are packages installed in package center BUT they are also containers running within docker. i am not sure how these will be able to be re-installed, but i think it should not matter since synology_docviewer does not really have any settings that appear to matter

**Comment by wallacebrf** [comment]
confirmed the warning in red text indicating that backing up the docker folder will take a long time. looks great.
