### ISSUE TITLE
v3.0 Beta test results - ArchwareP5

### ISSUE THREAD

**Issue by wallacebrf** [007revad/Synology_app_mover#24]
Synology_app_mover v3.0.15
DS920+ DSM 7.2.1-69057-4

could not stop the container. even 3 hours later, the container is stuck as "stopping" in package center. this is not an error with your code, but it made me think:

could you add a timer that waits perhaps 5 minutes max, and if the package is not stopped in 5 minutes to exit the script with an error. perhaps the same with starting packages to better handle weird app behavior.

**Comment by 007revad** [comment]
I've added a 5 minute timeout to stopping, and starting, packages, in [v3.0.17](https://github.com/007revad/Synology_app_mover/releases).

I verified that it works by setting it to 5 seconds and backing up Synology Calendar which takes about 30 seconds to start.
