### ISSUE TITLE
v3.0 Beta test results - package naming conventions

### ISSUE THREAD

**Issue by wallacebrf** [007revad/Synology_app_mover#25]
Synology_app_mover v3.0.15
DS920+ DSM 7.2.1-69057-4

perhaps add a note at the beginning of the package list that the packages may not be listed the same as they are shown in DSM. like the "Advanced Media Extensions" package appears to be called "codecpack" by your script, and "Data Deposit Box Cloud Backup" is called "DdbBackup" by the script. this would possible help people with some confusion going forward.

**Comment by 007revad** [comment]
New version [3.0.16](https://github.com/007revad/Synology_app_mover/releases) with the following changes: 
- Now shows package's display name.
- Bug fix for not processing Synology Calendar's `@calendar` folder.
- Bug fix for not processing Download Station's `@downloads` folder.

**NOTE** You need to run [update_backups.sh](https://github.com/007revad/Synology_app_mover/blob/test/update_backups.sh) once to copy each package's INFO file to your existing backups (so you don't have to backup all of them again).

**Comment by wallacebrf** [comment]
i have run the update_backups.sh file and will proceed with re-testing 

docker, calendar, and download station with the latest release
