### ISSUE TITLE
v3.0 Beta test results - Packages Requiring MariaDB

### ISSUE THREAD

**Issue by wallacebrf** [007revad/Synology_app_mover#26]
Synology_app_mover v3.0.15
DS920+ DSM 7.2.1-69057-4

for packages that are dependent on MariaDB like Joomla, MediaWiki, WordPress, vtigerCRM, etc your script does not perform any kind of backup of MariaDB. i do not think it would be wise to backup the entire MariaDB package as restoring that to restore just one app would possibly overwrite other still good databases. perhaps add a warning to the user that they should install PHPmyadmin to perform a manual export of their database(s).

example of an export screen shot
https://imgur.com/a/MYqQozi

**Comment by 007revad** [comment]
[v3.0.21](https://github.com/007revad/Synology_app_mover/releases)
- Added how to export/import database for packages that use MariaDB.

**Comment by 007revad** [comment]
Can you import a package's database while MariaDB is running?

**Comment by wallacebrf** [comment]
Yes I will be able to test that this week as I was out of my house this weekend with family
