### ISSUE TITLE
v3.0.18 - syno_app_mover.sh: line 1151: package_names["${package_name}"]: bad array subscript

### ISSUE THREAD

**Issue by wallacebrf** [007revad/Synology_app_mover#28]
i went to execute the script to try re-doing calendar, container manager, and download station. 
after pressing "2" for backup, i get an error and the "ready" question has the wrong item in the confirmation field. see blow. 

root@DS-920_spare:/volume3/volume3_share# bash syno_app_mover.sh
Synology_app_mover v3.0.18
DS920+ DSM 7.2.1-69057-4

Running from: /volume3/volume3_share/syno_app_mover.sh

1) Move
2) Backup
3) Restore
Select the mode: 2
You selected Backup

Backup path is: /volume3/volume3_share/backup_before_move

syno_app_mover.sh: line 1151: package_names["${package_name}"]: bad array subscript
Destination volume is /volume3

Ready to Backup  to /volume3/volume3_share/backup_before_move? [y/n]

here are lines 1150 through 1152. not sure if those lines are meant to be commented out?
#        if [[ ! ${package_names[*]} =~ "${package}|${package_name}" ]]; then
            package_names["${package_name}"]="${package}"
#        fi

**Comment by wallacebrf** [comment]
i also get the same error when trying option 1

root@DS-920_spare:/volume3/volume3_share# bash syno_app_mover.sh
Synology_app_mover v3.0.18
DS920+ DSM 7.2.1-69057-4

Running from: /volume3/volume3_share/syno_app_mover.sh

1) Move
2) Backup
3) Restore
Select the mode: 1
You selected Move

syno_app_mover.sh: line 1151: package_names["${package_name}"]: bad array subscript
1) /volume1
2) /volume2
3) /volume3
Select the destination volume:

**Comment by 007revad** [comment]
Strange. I'm not getting any error. 

What does `ls /var/packages` return?

Try uncommenting line 50 and 52. Then change line 50 to:
```
if [[ ! ${package_names[*]} =~ "${package}" ]]; then
```

**Comment by wallacebrf** [comment]
root@DS-920_spare:~# ls /var/packages
ActiveBackup            CloudSync         FileStation       MariaDB10     PHP7.3           RagicBuilder         SynoFinder                  Virtualization
ActiveBackup-GSuite     CMS               Git               MediaServer   PHP7.4           ReplicationService   SynologyApplicationService  VPNCenter
ActiveBackup-Office365  CodecPack         GlacierBackup     MediaWiki     PHP8.0           resiliosync          SynologyDrive               vtigerCRM
ActiveInsight           Contacts          GoodSync          MEGAcmd       PHP8.1           ScsiTarget           SynologyPhotos              WebDAVServer
AntiVirus               ContainerManager  HighAvailability  MinimServer   PHP8.2           SecureSignIn         SynoOnlinePack_v2           WebStation
Apache2.4               DdbBackup         HybridShare       NBR           phpMyAdmin       SMBService           SynoSmisProvider            WordPress
ArchiwareP5             DirectoryServer   HyperBackup       Node.js_v14   PlexMediaServer  SnapshotReplication  Tailscale
AudioStation            DNSServer         HyperBackupVault  Node.js_v16   PrestoServer     Spreadsheet          TeamViewer
BackupRestoreManager    DocumentViewer    IDrive            Node.js_v18   ProxyServer      SSOServer            TextEditor
BitDefenderForMailPlus  domotz            Joomla            Node.js_v20   Python2          StorageAnalyzer      UniversalViewer
C2IdentityLDAPAgent     DownloadStation   KodExplorer       NoteStation   Python3.9        StorageManager       USBCopy
Calendar                elephantdrive     LogCenter         OAuthService  QuickConnect     SupportService       VideoStation
Chat                    exFAT-Free        MailPlus-Server   Perl          RadiusServer     SurveillanceStation  VirtualHere

**Comment by wallacebrf** [comment]
i edited the script as you requested

```
        if [[ ! ${package_names[*]} =~ "${package}" ]]; then
            package_names["${package_name}"]="${package}"
        fi
```

and this is the results
```
root@DS-920_spare:/volume3/volume3_share# bash syno_app_mover.sh
Synology_app_mover v3.0.18
DS920+ DSM 7.2.1-69057-4

Running from: /volume3/volume3_share/syno_app_mover.sh

1) Move
2) Backup
3) Restore
Select the mode: 2
You selected Backup

Backup path is: /volume3/volume3_share/backup_before_move

syno_app_mover.sh: line 1151: package_names["${package_name}"]: bad array subscript
Destination volume is /volume3

Ready to Backup  to /volume3/volume3_share/backup_before_move? [y/n]
```

**Comment by wallacebrf** [comment]
no longer getting the error with 3.0.19
