### ISSUE TITLE
v3.0.19 - backing up PHP 8.0

### ISSUE THREAD

**Issue by wallacebrf** [007revad/Synology_app_mover#30]
the script appears to have to stop multiple packages, however it only lists the name of one of the dependent packages, the others it does not list the names

there is also a typo, you have "dependant" when it should be "dependent"

```
root@DS-920_spare:/volume3/volume3_share# bash syno_app_mover.sh
Synology_app_mover v3.0.19
DS920+ DSM 7.2.1-69057-4

Running from: /volume3/volume3_share/syno_app_mover.sh

1) Move
2) Backup
3) Restore
Select the mode: 2
You selected Backup

Backup path is: /volume3/volume3_share/backup_before_move

[Installed package list]
***i truncated for brevity****
Select the package to backup: 44
You selected PHP 8.0 in /volume1

Destination volume is /volume3

Ready to Backup PHP 8.0 to /volume3/volume3_share/backup_before_move? [y/n]
y

Stopping dependant packages
Stopping IDrive
Stopping
Stopping
Stopping
Stopping

Stopping PHP 8.0

Backing up /volume1/@appconf/PHP8.0
Backing up /volume1/@appdata/PHP8.0
Backing up /volume1/@apphome/PHP8.0
Backing up /volume1/@appshare/PHP8.0
Backing up /volume1/@appstore/PHP8.0
Backing up /volume1/@apptemp/PHP8.0

Starting PHP 8.0

Starting dependant packages
Starting IDrive
Starting
Starting
Starting
Starting

Finished backing up PHP 8.0
```

**Comment by 007revad** [comment]
> there is also a typo, you have "dependant" when it should be "dependent"

There was 17 "dependant" typos. I had functions, arrays and variables with "dependant" in their name!

I'm not sure what my recent changes have broken. Stopping dependent packages used to show their names. I'll install some apps that need php do some tests.

**Comment by 007revad** [comment]
I don't have any apps installed that depend on PHP 8.0

Can you tell me what the following command returns:
```
for p in /var/packages/*; do d=$(synogetkeyvalue "$p/INFO" install_dep_packages) && [ -n "$d" ] && echo "$(basename "$p") : $d"; done
```

**Comment by 007revad** [comment]
v3.0.22 [released](https://github.com/007revad/Synology_app_mover/releases)

- Fixed blank dependent package names if their INFO file has no displayname set.
