### ISSUE TITLE
v3.0.19 - script not backing up /volume1/web_packages directory

### ISSUE THREAD

**Issue by wallacebrf** [007revad/Synology_app_mover#31]
i have the following directories in my web_packages shared folder

mediawiki
kodexplorer
docker
phpmyadmin
vtigercrm
joomla
woordpress
idrive

should these be backed up too?

**Comment by 007revad** [comment]
Do they have data in them? I have the docker folder but it's empty.

For moving those packages they're not important.

For backing up those packages they definitely should be backed up.

**Comment by wallacebrf** [comment]
Not all of them have data but several do like phpmyadmin

**Comment by wallacebrf** [comment]
i looked through all folders. all of them contain data EXCEPT docker, that one is empty
 these all have data:
mediawiki, IDrive, joomla, kodexplorer, phpmyadmin, vtigercrm, wordpress

**Comment by 007revad** [comment]
v3.0.20 [released](https://github.com/007revad/Synology_app_mover/releases)

- Backup package's web_package folder if there is one.
- Restore package's web_package folder if there is one.
- Fix dependent typos (dependant).
