### ISSUE TITLE
Surveillance Station error

### ISSUE THREAD

**Issue by wallacebrf** [007revad/Synology_app_mover#33]
Synology_app_mover v3.0.37

Stopping Surveillance Station
Backing up /volume1/@appconf/SurveillanceStation
Backing up /volume1/@appdata/SurveillanceStation
Backing up /volume1/@apphome/SurveillanceStation
Backing up /volume1/@appshare/SurveillanceStation
Backing up /volume1/@appstore/SurveillanceStation
Backing up /volume1/@apptemp/SurveillanceStation
stat: cannot stat '/volume1/@ssbackup': No such file or directory
mkdir: invalid mode ‘’
Line 615: ERROR Failed to create directory!

**Comment by 007revad** [comment]
I just installed Surveillance Station and it didn't create the `@ssbackup` folder. 

I did recently change my DS720+ into a DVA1622 so I could install a the Deep Analytics version of Surveillance Station. Maybe that's what created the `@ssbackup` folder.

I'll add a check if the extra `@` folders exist to prevent errors.

**Comment by 007revad** [comment]
> stat: cannot stat '/volume1/@ssbackup': No such file or directory
> mkdir: invalid mode ‘’
> Line 615: ERROR Failed to create directory!

Did the script stop or continue past that error?

I've added a check that the extra @ folders exist to prevent errors.
https://github.com/007revad/Synology_app_mover/releases/tag/v3.0.38

**Comment by wallacebrf** [comment]
It stopped

**Comment by wallacebrf** [comment]
SS backed up fine this time. it said 

Stopping Surveillance Station
Backing up /volume1/@appconf/SurveillanceStation
Backing up /volume1/@appdata/SurveillanceStation
Backing up /volume1/@apphome/SurveillanceStation
Backing up /volume1/@appshare/SurveillanceStation
Backing up /volume1/@appstore/SurveillanceStation
Backing up /volume1/@apptemp/SurveillanceStation
**No /volume1/@ssbackup to backup**
Backing up /volume1/@surveillance
Starting Surveillance Station
