### ISSUE TITLE
Hyper Backup folder: @img_bkp_cache

### ISSUE THREAD

**Issue by ctrlaltdelete007** [007revad/Synology_app_mover#35]
Hi,
i moved Hyper Backup from Volume2 to Volume1, but it doesnt move the folder: @img_bkp_cache, is it possible to move it by hand?

**Comment by 007revad** [comment]
Are you having a problem with Hyper Backup after moving it to a different volume?

Originally the script did move `@img_bkp_cache` but it caused problems and I found moving it was not needed.

1. Moving "@img_bkp_cache" and editing synobackup.conf to point the repos to the new location causes backup tasks to show as offline with no way to fix them or delete them!
2. Thankfully HyperBackup recreates the data in @img_bkp_cache when the backup task is run, or a resync is done.

There is also `@img_bkp_mount` but it is always empty for me, and hyper recreates it on the new volume.

**Comment by ctrlaltdelete007** [comment]
No, no problems after moving.
Can i delete the folder @img_bkp_cache on Volume 2?

**Comment by 007revad** [comment]
> Can i delete the folder @img_bkp_cache on Volume 2?

Yes. 

I should probably update the script to delete the old `@img_bkp_cache` and `img_bkp_mount ` after moving Hyper Backup.

**Comment by ctrlaltdelete007** [comment]
I will run once all my backup tasks and than i will delete the folders.

**Comment by ctrlaltdelete007** [comment]
I just checked the @img_bkp_cache on Volume 1 its empty, so i am a little bit scared of deleting the folder on Volume 2, its around 30 GB

**Comment by 007revad** [comment]
Are you checking the `@img_bkp_cache` on volume 1 in WinSCP or via SSH? In WinSCP, as you probably know, you need to refresh to see changes.

First stop the Hyper Backup package.

The following will copy the contents and their permission from /volume2/@img_bkp_cache to /volume1/@img_bkp_cache 
```
sudo -i cp -prf "/volume2/@img_bkp_cache" "/volume1"
```

Then rename /volume2/@img_bkp_cache
```
sudo -i mv "/volume2/@img_bkp_cache" "/volume2/@img_bkp_cache_bak" 
```

Finally start Hyper Backup and check everything is okay, before deleting /volume2/@img_bkp_cache_bak.

**Comment by ctrlaltdelete007** [comment]
With WINSCP, i refreshed and also logged out an in, no chnages in Volume 1.
I will try your workaround and report.

**Comment by ctrlaltdelete007** [comment]
ok, that worked, i am running a backup task now and i can see modified files with actual time strings.

**Comment by 007revad** [comment]
Thanks for the update and confirmation.

I'll run some tests and update the script.

**Comment by ctrlaltdelete007** [comment]
One backup task to Hetzner storage box needs to connect new and its now downloading the index from hetzner storage.

**Comment by ctrlaltdelete007** [comment]
![image](https://github.com/007revad/Synology_app_mover/assets/13402151/19e82174-f0b3-41ca-980e-324d4f300901)

**Comment by ctrlaltdelete007** [comment]
OK, Backup Task now finished, the preparing took about 3 hours and than the task runs as normal.

**Comment by 007revad** [comment]
Moving Hyper Backup is now working. https://github.com/007revad/Synology_app_mover/releases/tag/v3.0.41
