### ISSUE TITLE
Container Manager: unable to remove ".syno.bak" containers after updating

### ISSUE THREAD

**Issue by talz13** [007revad/Synology_app_mover#37]
I successfully migrated my Container Manager to the new NVME volume this morning after the v3.0.40 update. When I ran the **Update available** button on one of the images with an update, it was successful at updating the container, but failed to remove the old version (with **.syno.bak** extension).

![image](https://github.com/007revad/Synology_app_mover/assets/3825115/2cc75ea3-cf99-4347-9826-e046bf039234)

The container is up and running properly, I just fear that I'll start accumulating these **.syno.bak** containers with no way to remove them.

I see the btrfs snapshot file under `/volume2/@docker/btrfs/subvolumes`, and it looks like all those files are `drwxr-xr-x root root` permission/owner:

![image](https://github.com/007revad/Synology_app_mover/assets/3825115/26194bbc-9961-48d9-a2c4-ba292241005a)

Do you have any idea what is preventing the removal of these snapshots? (I don't have Snapshot Replication or anything else set up on my ds920)

**Comment by 007revad** [comment]
Container Manager has been the most difficult app to reliably move. I have experienced the issue you are having, but I thought it was fixed. Though I've not updated an image after moving Container Manager.

By coincidence right now I actually have an image with an update available. I'm currently doing a full system backup so I keep returning to the current state (with an image that has an update available) so I can do some testing.

**Comment by 007revad** [comment]
What happens if run the following command?
```
docker system prune
```

**Comment by 007revad** [comment]
If `docker system prune` doesn't work you could try:
```
btrfs subvolume delete /volume2/@docker/btrfs/subvolumes/f36d05e480b865b1e79b30e2960f11771b43f3fa97220ec03cd2fd3affdaa93
```
Assuming I typed the btrfs snapshot folder name correctly from your images.

**Comment by talz13** [comment]
I made sure to have all my containers running and then ran `docker system prune`, but it didn't come up with anything to remove, probably same as your run:

```
jeff@synology01:~$ sudo -s docker system prune
Password: 
WARNING! This will remove:
  - all stopped containers
  - all networks not used by at least one container
  - all dangling images
  - all dangling build cache

Are you sure you want to continue? [y/N] y
Deleted Images:
deleted: 
deleted: 
deleted: 

Total reclaimed space: 0B
```

Only thing I noticed afterwards was that the other .bak container was now red, so it looks like it **tried** to remove it, but failed, and gave the same error on that container, pointing to its container/subvolume IDs as well.

I haven't had any luck with the `btrfs subvolume delete` yet, I get an error about "not a subvolume".

```
jeff@synology01:~$ sudo -s btrfs subvolume delete /volume2/@docker/btrfs/subvolumes/f36d05e480b865b1e79b30e2960f11771b43f3fa97220ec03cd2fd3affdaaf93
Password: 
ERROR: not a subvolume: /volume2/@docker/btrfs/subvolumes/f36d05e480b865b1e79b30e2960f11771b43f3fa97220ec03cd2fd3affdaaf93
```

It exists under the `/volume2/@docker/btrfs/subvolumes folder`:

```
jeff@synology01:~$ sudo -s ls -l /volume2/@docker/btrfs/subvolumes/ | grep "\sf36.*"
drwxr-xr-x 1 root root 316 Feb  1 13:17 f36d05e480b865b1e79b30e2960f11771b43f3fa97220ec03cd2fd3affdaaf93
drwxr-xr-x 1 root root 258 Feb  1 13:16 f36d05e480b865b1e79b30e2960f11771b43f3fa97220ec03cd2fd3affdaaf93-init
jeff@synology01:~$ 
```

I ran the command to list subvolumes, but don't see that particular id in the list:

```
jeff@synology01:~$ sudo btrfs subvolume list -p /volume2/@docker/btrfs/subvolumes
ID 256 gen 64447 parent 5 top level 5 path @syno
ID 258 gen 64450 parent 256 top level 256 path docker
ID 259 gen 8316 parent 256 top level 256 path @docker/btrfs/subvolumes/65b30a711f41c80dd31bf16959c7eb12d9e9d6769e04bbf5b880d86efa02a7de
ID 260 gen 8316 parent 256 top level 256 path @docker/btrfs/subvolumes/497882d44e7974f8210e1bd57f7f39ab287562da242e8c7617c20dea30805638
ID 261 gen 8316 parent 256 top level 256 path @docker/btrfs/subvolumes/75c5d87b548520daecffcdec82b78601a01f0b1f39f77b36bfb76ce817e3ef9b
ID 262 gen 8316 parent 256 top level 256 path @docker/btrfs/subvolumes/3e91c330f918d8f3aa86eac30d157b8b073838856d160ad5bc9506688c47e19b
ID 263 gen 8316 parent 256 top level 256 path @docker/btrfs/subvolumes/0c87173cc8ac338efada4ce509981b2e0b20e697a3f9efeb8e5d159cbab566ab
ID 264 gen 8316 parent 256 top level 256 path @docker/btrfs/subvolumes/d7af2db11ac5a49350a40040ad42e033d3148cf6543ade4493bf64ff9988295a
ID 265 gen 8316 parent 256 top level 256 path @docker/btrfs/subvolumes/3611284bc24765380841f77e5131a3b50d0329d21050b19b85fcb0735837e398
ID 266 gen 8316 parent 256 top level 256 path @docker/btrfs/subvolumes/d7c74933f5df11f7b51d9619d3df84b62614b013657c2136e5b035e52a481f2b
ID 267 gen 8316 parent 256 top level 256 path @docker/btrfs/subvolumes/e13cd6d39eebe46aa451fec8c5ca0397c1b51e25d59e7fb28c4ac70afbf8775e-init
ID 268 gen 33561 parent 256 top level 256 path @docker/btrfs/subvolumes/e13cd6d39eebe46aa451fec8c5ca0397c1b51e25d59e7fb28c4ac70afbf8775e
ID 269 gen 8316 parent 256 top level 256 path @docker/btrfs/subvolumes/2c262e186e9fba3c88f2642554f0a96da2f242b878f14847ceabb07d81693d90
ID 270 gen 8316 parent 256 top level 256 path @docker/btrfs/subvolumes/ae3284cedee40b9bfcccf5fd1b3cac55c21f5c7d83572e7fae86c8bde7839b80
ID 271 gen 8316 parent 256 top level 256 path @docker/btrfs/subvolumes/e4f72e9b215dcdda7c2e77c8eeb5654da1d990826f3ca93c00a337e4ea9296bb
ID 272 gen 8316 parent 256 top level 256 path @docker/btrfs/subvolumes/b519b018b8467ba815a2ef20b1de2ae1ba4a5095a28e11fdf8e58048b9cda742
ID 273 gen 8316 parent 256 top level 256 path @docker/btrfs/subvolumes/1ed721906b06b99b7565398c93725ce0cc81121e815019d390ffc975753fe246
ID 274 gen 8316 parent 256 top level 256 path @docker/btrfs/subvolumes/900438c9c4eccf97ed0fa40614a2ba40f96c6bc60433338e58bee9a5d16b4059
ID 275 gen 8316 parent 256 top level 256 path @docker/btrfs/subvolumes/ae6b36adf8fa55db80d0ee222cd7d7038b57a62180f7982075d7f3d40fd89a49
ID 276 gen 8316 parent 256 top level 256 path @docker/btrfs/subvolumes/0fd93e24d6bf761dea53bf68219c015333c6c738f47188e0bf3b42bdb4dcd755
ID 277 gen 8316 parent 256 top level 256 path @docker/btrfs/subvolumes/75e4ff92e634818e0ff7638bbeaaf945463f7b5324af1fe6c6b3dda2d4009e8e-init
ID 278 gen 58310 parent 256 top level 256 path @docker/btrfs/subvolumes/75e4ff92e634818e0ff7638bbeaaf945463f7b5324af1fe6c6b3dda2d4009e8e
ID 279 gen 63702 parent 256 top level 256 path PlexMediaServer
ID 280 gen 50127 parent 256 top level 256 path @sharesnap
ID 281 gen 50127 parent 280 top level 280 path @sharesnap/docker
ID 283 gen 50118 parent 280 top level 280 path @sharesnap/PlexMediaServer
```

Not sure if any of this has to do with permissions on the `@docker` folder, I assume it preserved permissions when the script moved it from volume1 to volume2, but here's what I see right now:

<img width="410" alt="image" src="https://github.com/007revad/Synology_app_mover/assets/3825115/bd2d86e7-1de1-437b-8d8c-d7f44a0556b6">

**Comment by 007revad** [comment]
I actually deleted them using WinSCP's gui. So when I wrote "This worked for me." I meant deleting the affected subvolumes worked for me.

Try this:
```
sudo rm -rf /volume2/@docker/btrfs/subvolumes/e13cd6d39eebe46aa451fec8c5ca0397c1b51e25d59e7fb28c4ac70afbf8775e-init
sudo rm -rf /volume2/@docker/btrfs/subvolumes/e13cd6d39eebe46aa451fec8c5ca0397c1b51e25d59e7fb28c4ac70afbf8775e

sudo rm -rf /volume2/@docker/btrfs/subvolumes/75e4ff92e634818e0ff7638bbeaaf945463f7b5324af1fe6c6b3dda2d4009e8e-init
sudo rm -rf /volume2/@docker/btrfs/subvolumes/75e4ff92e634818e0ff7638bbeaaf945463f7b5324af1fe6c6b3dda2d4009e8e
```

**Comment by talz13** [comment]
Ok, I've updated each of my container images, and manually removed those extraneous folders from the subvolumes, on a case-by-case basis.
I'm wondering if it has anything to do with ones that were created before the migration, and if they will be able to update next time. I'll give it a week or so and see if I can update again next time.

**Comment by 007revad** [comment]
I'm fairly sure once the subvolumes that were moved from volume 1 have been deleted there won't be further issues when updating images or containers.

I'm going to try changing the script to **not** move the subvolumes. They're only snapshots and docker will create new snapshots when needed, so there's really no need for the script to move them (or copy them) to the new volume.

**Comment by talz13** [comment]
Also given that I have 641 items under subvolumes, and only have 11 containers, seems like there would be many that should not be needed anymore 😄 
Is there any safe way of identifying subvolumes not in use under the @docker folder? Are they all fair game to remove without causing any issue for the existing / running containers?

**Comment by 007revad** [comment]
Wow. I've only got 28 on volume 1, and 22 on volume 2.
- The 28 were modified on 3 different dates: 18-03-2024, 27-02-2024 and 02-02-2024.
- All 3 dates groups contain 1 or 2 subvolumes that end with -init.

1. I just stopped Container Manager (that has been moved to volume 2).
2. Deleted all 28 subvolumes on volume 1.
3. Started Container Manager.
4. Now all my containers have a red dot and the log has errors with "no file or directory" for each container's subvolume.

The missing subvolume names aren't subvolumes that exist on volume 2, except for 1 but that container is also broken.

So deleting all of them is NOT an option. 

And I have to figure out why  some of my containers are looking for their subvolumes on volume 1.

**Comment by talz13** [comment]
There may be some practicality to compare the subvolume ids from the `sudo btrfs subvolume list -p /volume2/@docker/btrfs/subvolumes` command, with what is actually listed in the `/volume2/@docker/btrfs/subvolumes` directory. If you just completely removed everything from the subvolumes folder, that may lead to the condition you saw, with Container Manager complaining about "no file or directory".

If you can restore and try comparing the results of those, you could try removing anything that is **not present** on the list of `btrfs subvolume list -p`, as they might not be connected to anything in Container Manager.

Of course, it could be something on my side that resulted in over 600 folders being located under the subvolumes directory, since yours didn't seem to have nearly that many. Mine have dates going back to 2021, so maybe it's something that has been growing for a while on my side.

**Comment by 007revad** [comment]
I checked my DS1821+ and it has a few containers at the moment but has 120 subvolumes. Apparently docker not cleaning up old data is a common problem.

I played around with some `docker prune` commands and lost some unused volumes I had in `/volume1/docker`

I tried shutting down container manager, deleting all subvolumes, then starting container manager but that just resulted in losing everything.

I missed the fact that your `sudo btrfs subvolume list -p` was actually 
`sudo btrfs subvolume list -p /volume2/@docker/btrfs/subvolumes`
because the last half wrapped to the next line.

That command lists 11 subvolumes, and I can see which are the orphan subvolumes. I'm going to write a little test script to delete the orphan subvolumes and see what happens.

**Comment by 007revad** [comment]
> There may be some practicality to compare the subvolume ids from the `sudo btrfs subvolume list -p /volume2/@docker/btrfs/subvolumes` command, with what is actually listed in the `/volume2/@docker/btrfs/subvolumes` directory.

I've written a test script: https://github.com/007revad/Synology_app_mover/blob/test/docker_cleanup.sh

It prints 3 lists:
1. `@docker`/btrfs/subvolumes list
2. btrfs subvolume list
3. orphan subvolume list

If you run it and compare the `@docker/btrfs/subvolumes list` to the `btrfs subvolume list` the difference should be the same as the `orphan subvolume list`

Next I'll get the script to delete the orphans and see what happens to my containers.

**Comment by talz13** [comment]
Could you test the script by simply moving the orphans out, then you can validate the containers and move the folders back if something breaks. 

Looking forward to cleaning up these orphans!

**Comment by 007revad** [comment]
I've moved container manager and then updated an image which resulted in:
1. The image update getting stuck at 96%.
2. An old image with .syno.bak appended to it's name.
3. The same issue you had trying to delete old containers after updating them.

So I was able to test the script to delete the orphan containers, and it works great.
https://github.com/007revad/Synology_docker_cleanup

<br>

While writing the script I googled `container manager "syno.bak" image` only found 3 results.
1. Your reddit post.
2. Your reddit profile.
4. An interesting Chinese blog from 2 months ago: https://juejin.cn/post/7327353593890193459

From that Chinese blog you can find images that don't have the `<latest>` tag with:
```
sudo docker images
```
Then with the image id of an old image you can delete it with:
```
sudo docker rmi <image id>
```
I think I'll add this to the syno_docker_cleanup script.

**Comment by 007revad** [comment]
v1.2.3 now also removes orphaned images
https://github.com/007revad/Synology_docker_cleanup/releases

**Comment by talz13** [comment]
Closing this issue, opened new issue on the Synology_docker_cleanup...

https://github.com/007revad/Synology_docker_cleanup/issues/4
