### ISSUE TITLE
After updating it doesn't wanna stop app.

### ISSUE THREAD

**Issue by Rasmusho12** [007revad/Synology_app_mover#44]
After updating from 3.0.41 to 3.0.45 it doesn't want to stop the app. It fails to do so, however when checking directly on the synology, the app has stopped.
![image](https://github.com/007revad/Synology_app_mover/assets/22321590/2f305c6e-b4a9-4908-86ce-ca089ddee927)

After downgrading there is no problem at all
![image](https://github.com/007revad/Synology_app_mover/assets/22321590/a276e614-7e98-4788-816a-844b020aacd7)

**Comment by 007revad** [comment]
- v3.0.41 had separate code for DSM 7.2 and newer and DSM 7.1.1 and older.
- v3.0.45 has combined the 2 sections of code into 1 section.

With DSN Server running what does the following command return?
```
sudo /usr/syno/bin/synopkg status DNSServer
```
And the same command when DSN Server is stopped?

**Comment by dakky** [comment]
have the same issue:
the problem is here:
```
root@hive /volume1/scripts/Synology_app_mover-3.0.45 $ /usr/syno/bin/synopkg status MailServer; echo $?
{"aspect":{"active":{"status":"running","status_code":0,"status_description":"retrieve from status script"}},"description":"Status: [0], package is started","package":"MailServer","status":"running"}
0
``` 
 the return code is always `0` 

DSM Version: DSM 7.1.1-42962 Update 6

**Comment by dakky** [comment]
Probably better:
```
root@hive /volume1/scripts/Synology_app_mover-3.0.45 $ /usr/syno/bin/synopkg is_onoff MailServer; echo $?
package MailServer isn't turned on, status: [262]
1
root@hive /volume1/scripts/Synology_app_mover-3.0.45 $ /usr/syno/bin/synopkg is_onoff MailServer; echo $?
package MailServer is turned on
0
```

**Comment by 007revad** [comment]
@dakky @Rasmusho12 

I've released a new version that fixes this issue.
https://github.com/007revad/Synology_app_mover/releases/tag/v3.0.46
