### ISSUE TITLE
HyperBackup Cache

### ISSUE THREAD

**Issue by zzecool** [007revad/Synology_app_mover#45]
Hello there i read your file and got a bit confused about the move of /volume*/@img_bkp_cache

You comment out the editing of synobackup.conf and the move of cache folder and i wonder why ?

Im asking because when the Synology is preparing the backup task there is very intense HDD usage and if you have your synology on desk this is a problem.

Moving the cache folder to a flash drive will fix this "problem"

Thanks  : )

**Comment by 007revad** [comment]
Moving `@img_bkp_cache` **AND** editing synobackup.conf to point the repos to the new location causes backup tasks to show as offline with no way to fix them or delete them!

When HyperBackup starts it automatically updates synobackup.conf to point to the volume it's installed on. It also creates a new, empty, `@img_bkp_cache` if it is missing.

So I just move `@img_bkp_cache`.
