### ISSUE TITLE
Container Manager Move failed - No more containers

### ISSUE THREAD

**Issue by Sir-Bacon** [007revad/Synology_app_mover#46]
**Script version:** 3.0.45
**NAS model:** DS918+ with 16 GB RAM
**DSM version:** DSM 7.2-64570 Update 3

First, thanks for the script, I moved almost all packages, excluding 1, from volume1 to volume2. When I tried to move Container Manager it failed to do so. Screenshots below.
After failing I restarted CM in the DSM webpage and it showed no containers. I have the dockers already on volume2, the data is still there. Furthermore, on volume1 there is both an @docker as well as an @docker_backup folder.

Any tips on how I can get my containers back up and running?

![image](https://github.com/007revad/Synology_app_mover/assets/7254913/713e4505-f8b8-459d-904b-0fb417ded1f2)
![image](https://github.com/007revad/Synology_app_mover/assets/7254913/6a8746e9-a30a-4330-b651-d4967fd8f4bd)
![image](https://github.com/007revad/Synology_app_mover/assets/7254913/7af386f6-1b3c-487b-8e8c-ca3c763a7662)

**Comment by 007revad** [comment]
@Sir-Bacon 

Sorry, I came here to reply to you 4 days ago but got side-tracked and forgot to come back and reply. Did you sort it out?

**Comment by 007revad** [comment]
The Restore option only works if you previously used the Backup option to backup the package. 

You could stop Container Manager then copy the contents of @docker_backup from Volume1 to `@docker` on Volume2. You want to keep their permissions so it's better to do it via SSH. And copying is safer than moving, so you still have the backup.
```
sudo -i cp -prf "/volume1/@docker_backup" "/volume2/@docker"
```

You also want to check that all the Container Manager symlinks point to volume 2. You can view, and edit, them in WinSCP.

![symlinks-1](https://github.com/007revad/Synology_app_mover/assets/39733752/dd6650d1-4446-4c08-a747-da2a0cd21925)

There's also these other 2 symlinks you should check:
```
/usr/syno/etc/packages/ContainerManager  ->  /volume2/@appconf/ContainerManager
/var/packages/ContainerManager/var/docker  ->  /volume2/@docker
```

I just noticed on my DS1821+ that `/var/packages/ContainerManager/var/docker` is no longer a symlink pointing to `/volume2/@docker`. Instead it's now a folder that contains what is normally in `@docker`. I don't know if I've broken it or if DSM 7.2.1 Update 4 changed it.

I much uninstall Container Manager and reinstall it and check `/var/packages/ContainerManager/var/docker` again.

**Comment by Sir-Bacon** [comment]
> The Restore option only works if you previously used the Backup option to backup the package.
A backup was performed as part of the moving process, not as a separate task (see 2nd screenshot).

> You could stop Container Manager then copy the contents of @docker_backup from Volume1 to `@docker` on Volume2. You want to keep their permissions so it's better to do it via SSH. And copying is safer than moving, so you still have the backup.
> 
> ```
> sudo -i cp -prf "/volume1/@docker_backup" "/volume2/@docker"
> ```
> 
I will try the copying you suggested tonight, thanks for the total command

> You also want to check that all the Container Manager symlinks point to volume 2. You can view, and edit, them in WinSCP.
> 
> ![symlinks-1](https://private-user-images.githubusercontent.com/39733752/322425180-dd6650d1-4446-4c08-a747-da2a0cd21925.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMxNzYyMzMsIm5iZiI6MTcxMzE3NTkzMywicGF0aCI6Ii8zOTczMzc1Mi8zMjI0MjUxODAtZGQ2NjUwZDEtNDQ0Ni00YzA4LWE3NDctZGEyYTBjZDIxOTI1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE1VDEwMTIxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE5MDEyOTMyNjBkNzkwZTg4MDdkOWE0YjBlNDVjMDQzYTg1NjVmNDliMzBhNDE5N2ExYzFhNjQyZGU5NDZkMjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wuR3o39DTiRN2pMcfXjHTzpel-sBRNJLOkiBg6PkreU)
> 
> There's also these other 2 symlinks you should check:
> 
> ```
> /usr/syno/etc/packages/ContainerManager  ->  /volume2/@appconf/ContainerManager
> /var/packages/ContainerManager/var/docker  ->  /volume2/@docker
> ```
Will do that as well, after the copying
> 
> I just noticed on my DS1821+ that `/var/packages/ContainerManager/var/docker` is no longer a symlink pointing to `/volume2/@docker`. Instead it's now a folder that contains what is normally in `@docker`. I don't know if I've broken it or if DSM 7.2.1 Update 4 changed it.
I believe I am still on Update 3, but will check tonight

> 
> I much uninstall Container Manager and reinstall it and check `/var/packages/ContainerManager/var/docker` again.

**Comment by Sir-Bacon** [comment]
OK, some results.

1. The copy worked, I estimate it took around half an hour
2. I checked the symlinks (In SSH, could not get WinSCP to show all files) and these are all ok, see screenshot below
3. I checked the symlink for ContainerManager, that is ok, see 2nd screenshot below
4. I checked the symlink for docker, that was still pointing to volume 1. I removed it and tried to get a new in, but got an error message, see screenshot 3 and 4 below

My DSM version is 7.2-64750 Update 3, telling me I am up-to-date.

In /usr/syno/etc/packages/ I also found a symlink for Docker which was still pointing to volume1, see screen shot 5 below.

At this point I have not restarted ContainerManager as 1 symlink is not pointing to volume2. How to get that in place?

![image](https://github.com/007revad/Synology_app_mover/assets/7254913/2ab76a4d-af70-4a4a-8520-94f146e9103a)

![image](https://github.com/007revad/Synology_app_mover/assets/7254913/250f1a3a-2386-45f5-85b5-56dd5efe9ff9)

![image](https://github.com/007revad/Synology_app_mover/assets/7254913/c390ca59-c943-4abe-868f-6c6526dccde0)

![image](https://github.com/007revad/Synology_app_mover/assets/7254913/ceec1416-4c6f-4a1c-a75e-2989570399e7)

![image](https://github.com/007revad/Synology_app_mover/assets/7254913/11478457-9f09-40a0-abad-009e89d8a714)

**Comment by 007revad** [comment]
You can edit symlinks in WinSCP if you are connected as root.

Otherwise you need to delete the symlink and then create a new symlink.
```
sudo -i
rm /var/packages/ContainerManager/var/docker/
ln -s /volume2/@docker /var/packages/ContainerManager/var/docker/
```

**Comment by 007revad** [comment]
I'm not sure where you saw what's in your last sceenshot?

You need to move the Docker shared folder in Control Panel. 

1. Stop Container Manager.
2. Go to 'Control Panel > Shared Folders'.
3. Select your Docker shared folder and click Edit.
4. Change Location to volume 2.
5. Click on Advanced and check that 'Enable data checksums' is selected. 'Enable data checksums' is only available if moving to a Btrfs volume.
6. Click Save.

**Comment by Sir-Bacon** [comment]
I retried WinSCP to work as root, using https://emby.media/community/index.php?/topic/103636-how-to-access-synology-nas-as-admin-or-superuser-using-winscp/, but got an error message back. Must be something I did wrong.
Anyway, I then tried via SSH. This seems to work fine, I recreated the symlink. I did have to change the create command slightly:
`ln -s /volume2/@docker /var/packages/ContainerManager/var/`
![image](https://github.com/007revad/Synology_app_mover/assets/7254913/2e42fe31-68c9-444f-8d10-f294998be06b)

I checked the location of the Shared Docker folders. That is already on Volume2, with 'Enable data checksums' already checked.

Then I restarted ContainerManager, but no luck. Still completely empty. 'No Containers'. 
Perhaps you have another idea. Otherwise I will simply create new containers. First trying to reuse the old data, otehrwise I'll start from scratch.

**Comment by 007revad** [comment]
I just uninstalled Container Manager, but did NOT tick the option to delete containers, images or my docker shared folder. I then checked that all the `@` folders were gone. Then I reinstalled Container Manager and it again has a folder named `/var/packages/ContainerManager/var/docker/` instead of a symlink pointing to `/volume#/@docker`. 

`/var/packages/ContainerManager/var/docker/` contains all the folders and files that `/volume#/@docker` used to contain. 

I've got to work if this changed with a DSM update or a Container Manager update.

I would suggest uninstalling Container Manager, but don't tick the box to delete everything, then reinstall Container Manager on volume 2.

**Comment by Sir-Bacon** [comment]
I just uninstalled and re-installed ContainerManager, but still no containers in sight.

For me, the next step will be to start creating the same containers as I had, pointing to the shared docker directory. (I will make a backup of that directory first) Hopefully the containers should then spring back to life. This I will do in the weekend, no time to do it before then.

**Comment by Sir-Bacon** [comment]
I tried to re-install a single container, Eclipse-Mosquitto. This turned out to be drama. Several non-specific failure messages, including 'port already in use'. I removed and re-installed Container Manager, restarted the NAS, all without success. So, still no running containers.
The next step is a bit unsure, resetting completely the NAS? Seems a bit over-the-top to get CM running again.
If I remove CM, are there any specific folders I need to delete  as well?

**Comment by 007revad** [comment]
Backup the contents of your docker shared folder. Then when you uninstall Container Manager tick the box to "Delete the items listed above when uninstalling the package". This will not only uninstall Container Manager but also delete all the Images, Containers and docker shared folder.

Then recreate your docker shared folder and restore it's files. Then install Container Manager.

**Comment by Sir-Bacon** [comment]
Well, did all that and got a container running. Home-Assistant started completely normally.
Eclipse-Mosquitto not, still complaining about a port in use, but it seems there may be something else going on (https://github.com/eclipse/mosquitto/issues/2866). So perhaps all my complaints were simply the result of another error.
For now it seems resolved.
Thanks for all the help!

**Comment by Sir-Bacon** [comment]
Closed as for me issue is resolved. In the end I made new containers.
Mosquitto is also up and running, see issue there.

If this issue is resolved with the app mover script, I leave that to @007revad
