### ISSUE TITLE
Confirmation before starting after move?

### ISSUE THREAD

**Issue by lnlyssg** [007revad/Synology_app_mover#8]
Would it be possible/a good idea to have a confirmation before starting the package after the move?

**Comment by 007revad** [comment]
I've been working an update for the script which actually now includes asking before starting ContainerManager/Docker or PlexMediaServer.

I could easily change it so it asks for all packages.

**Comment by lnlyssg** [comment]
ContainerManager was the one that caused a problem earlier so I'm glad to hear that's in hand 🙂

**Comment by 007revad** [comment]
I've released a new version that asks if you want to start the package after moving it.
https://github.com/007revad/Synology_app_mover/releases/tag/v2.0.6
