### ISSUE TITLE
Unable to remove volume where Synology drive was moved from.

### ISSUE THREAD

**Issue by hstubbe88** [007revad/Synology_app_mover#80]
When i try to remove volume 1 it says i still have synology drive installed on volume 1.
I moved synology drive from volume 1 to volume 3.
In package center it says it's installed on volume 3.
All symlinks seem correct.

root@NasServer:/var/packages/SynologyDrive# ls -l
total 104
drwxr-xr-x 3 root root  4096 Jun 23 22:35 conf
-rw-r--r-- 1 root root     0 Jun 23 22:36 enabled
lrwxrwxrwx 1 root root    31 Jun 23 22:35 etc -> /volume3/@appconf/SynologyDrive
lrwxrwxrwx 1 root root    31 Jun 23 22:35 home -> /volume3/@apphome/SynologyDrive
-rw-r--r-- 1 root root 92386 Jun 23 22:35 INFO
drwxr-xr-x 3 root root  4096 Jun 23 22:35 scripts
lrwxrwxrwx 1 root root    32 Jun 23 22:35 share -> /volume3/@appshare/SynologyDrive
lrwxrwxrwx 1 root root    32 Jun 23 22:35 target -> /volume3/@appstore/SynologyDrive
lrwxrwxrwx 1 root root    31 Jun 23 22:35 tmp -> /volume3/@apptemp/SynologyDrive
lrwxrwxrwx 1 root root    31 Jun 23 22:35 var -> /volume3/@appdata/SynologyDrive
drwxr-xr-x 2 root root  4096 Jun 23 22:35 WIZARD_UIFILES

**Comment by 007revad** [comment]
What do the following commands return?
```
synogetkeyvalue /var/packages/SynologyDrive/etc/sharesync/monitor.conf system_db_path

synogetkeyvalue /var/packages/SynologyDrive/etc/sharesync/service.conf volume

readlink /var/packages/SynologyDrive/etc/repo

grep 'volume' /var/packages/SynologyDrive/etc/sharesync/daemon.conf

du /volume3/@SynologyDriveShareSync

du /volume3/@synologydrive

du /volume1/@SynologyDriveShareSync

du /volume1/@synologydrive
```

**Comment by 007revad** [comment]
Also, where is Synology Drive's database located?
```
synogetkeyvalue /var/packages/SynologyDrive/etc/db-path.conf db-vol
```
If it's on volume 1 you need to change the location to volume 3.
1. Open 'Synology Drive Admin Console'.
2. Click Settings.
3. Change Location to volume 3.
4. Click Apply.

**Comment by hstubbe88** [comment]
The synology drive database is located on volume 3.

But some of things are located on volume 1, how do i move those?

root@NasServer:/# synogetkeyvalue /var/packages/SynologyDrive/etc/sharesync/monitor.conf system_db_path
/volume1/@SynologyDriveShareSync/db/sys.sqlite
root@NasServer:/# synogetkeyvalue /var/packages/SynologyDrive/etc/sharesync/service.conf volume
/volume1
root@NasServer:/# grep 'volume' /var/packages/SynologyDrive/etc/sharesync/daemon.conf
db_temp_directory="/volume1/@SynologyDriveShareSync/@tmp"
filter_db_path="/volume1/@SynologyDriveShareSync/db/filter.sqlite"
fstat_db_path="/volume1/@SynologyDriveShareSync/db/file-status.sqlite"
history_db_path="/volume1/@SynologyDriveShareSync/db/history.sqlite"
log_file_path="/volume1/@SynologyDriveShareSync/log/dscc.log"

**Comment by 007revad** [comment]
Is `@synologydrive` on volume 1, volume 3, or a copy of both volumes?

Is `@SynologyDriveShareSync` on volume 1, volume 3, or a copy of both volumes?

**Comment by 007revad** [comment]
Assuming your `@synologydrive` and `@SynologyDriveShareSync` are on volume3

1. Stop Synology Drive.
2. Run these commands:

```
sudo -i

synosetkeyvalue /var/packages/SynologyDrive/etc/sharesync/monitor.conf system_db_path "/volume3/@SynologyDriveShareSync/db/sys.sqlite"

synosetkeyvalue /var/packages/SynologyDrive/etc/sharesync/service.conf volume /volume3

sed -i 's|'/volume1'|'/volume3'|g' /var/packages/SynologyDrive/etc/sharesync/daemon.conf

chmod 644 /var/packages/SynologyDrive/etc/sharesync/daemon.conf
```
3. Start Synology Drive.

**Comment by hstubbe88** [comment]
Is @synologydrive on volume 1, volume 3, or a copy on both volumes?
Volume 3

Is @SynologyDriveShareSync on volume 1, volume 3, or a copy on both volumes?

Copy on both volumes 
I just uninstalled synology drive and reinstalled it again on volume 3.
Now i can remove volume 1 .
The rest of my packages moved perfectly thanks to your awesome script !!
Thanks!
