### ISSUE TITLE
Missing -v or --verbose mode flag

### ISSUE THREAD

**Issue by DanBurkhardt** [007revad/Synology_app_mover#81]
Great work on this tool! It is really needed, I was very surprised to learn the only official DSM method was uninstall/reinstall. 

I ran this application last today to move one of the official synology apps and it worked great-- but when I tried to move the Docker package I had issues (created an [issue for that here](https://github.com/007revad/Synology_app_mover/issues/82))

Would be great if there was a -v or --verbose flag supported so we can track the bread crumbs to diag. 

Thanks for taking the suggestion,
Dan

**Comment by 007revad** [comment]
The script stops the Container Manager (or Docker) package so there should not be any containers still running.

Moving, or backing up, the `@docker` folder can take hours depending on the size and quantity of containers. 

There are 2 undocumented options, but they can only be used one at a time: 
- `--trace`
- `--debug`

Trace prints information on where each function was called from. If you only want to see the trace output from after you answer  "y" you can insert a line at line 1990 and add `trace=yes`

If you only want to debug the whole script you can:
1. Insert a line at line 1990 and add `debug on`
2. Insert a line at line 2025 and add `debug off`

**Comment by DanBurkhardt** [comment]
Thanks for the response. Might as well just add those flags to the readme, I’m sure others will need them eventually too. I’ll give them a try.I assume the move is probably not hanging in that case, but taking a long time. For a situation where a process has to move above a certain file size, I would say some kind of progress indicator would be helpful so users don’t quit the operation prematurely. Doesn’t matter how long it takes as long as IMO I just know it’s working on something.On Jun 28, 2024, at 4:12 AM, Dave Russell ***@***.***> wrote:﻿
The script stops the Container Manager (or Docker) package so there should not be any containers still running.
Moving, or backing up, the @docker folder can take hours depending on the size and quantity of containers.
There are 2 undocumented options, but they can only be used one at a time:

--trace
--debug

Trace prints information on where each function was called from. If you only want to see the trace output from after you answer  "y" you can insert a line at line 1990 and add trace=yes
If you only want to debug the whole script you can:

Insert a line at line 1990 and add debug on
Insert a line at line 2025 and add debug off

**Comment by DanBurkhardt** [comment]
Works! Thanks again.
