### ISSUE TITLE
Failed to Move or Backup Docker, package & container hosed after attempt; custom config / possible edge case

### ISSUE THREAD

**Issue by DanBurkhardt** [007revad/Synology_app_mover#82]
I ran this application last today to move one of the official synology apps and it worked great-- but when I tried to move the Docker package, it threw an error (line 388) without much in the way of details. 

Subsequent attempts to either move or backup Docker (installed normally via package center) either failed, or just hung.. but I couldn't tell if it was working or not.

Some context that might be helpful:

- I did happen to have a container running with docker when I started the tool
    - I figured stopping Docker would be handled internally first by stopping all containers.. now I am not so sure that's what happened. In any case, it still doesn't explain why I couldn't even backup the Docker config.

- The container running was built using a manually added docker image from my private dockerhub account, it was  not a public image
    - A long time ago when I first built the running container, I manually ssh'd into the NAS, logged into my private account, and then pulled the image. Once done, I was it pop in the UI, and switched to the DSM interface to configure, build, and run the container
    
-  The Docker package was configured to automatically restart the running container in the event of crash or DSM reboot
    
- I did also have several images pulled from the dockerhub public registry, and images built with those as well, but all were stopped 

In any case, when I stopped the tool and tried starting Docker from the package center, it failed to start. Installation seems like it is hosed now, all containers lost.

Seems like the private docker container could be an edgy case, idk. I see Docker is on the verified package list

**Comment by DanBurkhardt** [comment]
Though the Docker package initially failed after the first attempt to move / back it up, it seems to have kicked back on and it working fine.

Sounds like this is more related to lack of progress indication, since Docker can have tons of data from images / containers.

Would rec some evaluation of the total file size of a move / backup operation prior to starting it, and above a certain limit (maybe 1gb?) start a progress indicator, otherwise it looks to me like the script is just hanging, and I quit early instead of waiting.

**Comment by 007revad** [comment]
There is a progstatus function (on line 325) that calls a progbar function (on oine 307) that shows a progress bar of dots at the end of each line that's printed.

Like the following (except it's done on 1 row), incrementing every 0.2 seconds
```
Moving @docker to volume2 .
Moving @docker to volume2 ..
Moving @docker to volume2 ...
Moving @docker to volume2 ....
Moving @docker to volume2 .....
Moving @docker to volume2 ......
Moving @docker to volume2 .......
```
If/when the progress bar gets to column 80 it starts again.

Did you not see the progress dots at all for any process?

**Comment by DanBurkhardt** [comment]
Nope, no process ever showed a progress bar like that. Personally though I would prefer a percentage representation for more accurate monitoring.

**Comment by 007revad** [comment]
So you didn't notice the little ... like in this video?
https://github.com/007revad/Synology_app_mover#video

**Comment by DanBurkhardt** [comment]
Buddy, I’m telling you, it did not work on my system. Just didn’t happen, no “…”. I’m just telling you my experience. Not at my machine right now, but I can post a screenshot or a video whenever I get access to it again.On Jun 28, 2024, at 9:37 AM, Dave Russell ***@***.***> wrote:﻿
So you didn't notice the little ... like in this video?
https://github.com/007revad/Synology_app_mover#video
