### ISSUE TITLE
SynologyDrive Database Issue

### ISSUE THREAD

**Issue by sysvar** [007revad/Synology_app_mover#9]
I did say on reddit that everything went fine but i spoke to soon. 

I have found a bug when trying to move **SynologyDrive** using [syno_app_mover.sh](https://github.com/007revad/Synology_app_mover/blob/main/syno_app_mover.sh) where once you reopen the GUI package it says the database is corrupted and you should delete it (see screenshot). I didn't delete it and just moved it back using [syno_app_mover.sh](https://github.com/007revad/Synology_app_mover/blob/main/syno_app_mover.sh), it resolve the issue. 

![SynoDrive](https://github.com/007revad/Synology_app_mover/assets/18425808/d7c801a1-6b90-466c-b139-e63bb5d472e9)

I did a brief investigation but couldn't find the issue, I'm sorry. Other than that I tried the move the package twice just to be sure it wasn't a random bug.

I have two volumes on my NAS. 
- Volume 1 is where is was originally (working)
- Volume 2 is where i moved it where i face the error.

I should also note that in SynologyDriveAdmin the whole time, the database location in the GUI was set to volume 2 (see screenshot), the task completed successfully a few weeks ago and I've left that setting without change since then so that shouldn't really have affected what I did 2/3 days ago with [syno_app_mover.sh](https://github.com/007revad/Synology_app_mover/blob/main/syno_app_mover.sh).

![SynoDrive2](https://github.com/007revad/Synology_app_mover/assets/18425808/82e88f14-5a7f-4c26-91fa-506ad6db68b1)

Other than that, app is amazing, thank you!

**Comment by 007revad** [comment]
I've just installed Synology Drive to have a look... and it's indexing 50,000 files!?!?

I notice there's a `/volume1/@SynologyDriveShareSync/conf` folder (which for me is empty, probably because I haven't setup anything yet).

What do the following commands return?
```
ls /volume1/@SynologyDriveShareSync/conf
```
```
ls /volume2/@SynologyDriveShareSync/conf
```

Do you know is the Synology Drive database stored in `/volume2/@synologydrive` or in some other folder?

What do the following commands return?
```
ls /volume1 | grep -i '^@synologydrive'
ls /volume2 | grep -i '^@synologydrive'
```

**Comment by sysvar** [comment]
Yes that sounds pretty normal for indexing, handy app. Thanks for investigating.

**I found the database** (well files), matches the size of the screenshot in first post.
```
root@dsm:/# du -h --threshold=6GB /volume2/@synologydrive | sort -h 
6.3G	/volume2/@synologydrive/@sync/sign
7.8G	/volume2/@synologydrive/@sync
8.3G	/volume2/@synologydrive
```

Your Q response 1
```
root@dsm:~# ls -lah /volume1/@SynologyDriveShareSync/*
/volume1/@SynologyDriveShareSync/conf:
total 0
drwxr-xr-x 1 root root  0 Jun  8  2020 .
drwxr-xr-x 1 root root 40 Apr 29  2023 ..

/volume1/@SynologyDriveShareSync/db:
total 120K
drwxr-xr-x 1 root root 214 Jan  7 22:52 .
drwxr-xr-x 1 root root  40 Apr 29  2023 ..
-rw-r--r-- 1 root root 21K Jun  9  2020 filter.sqlite
-rw-r--r-- 1 root root 32K Jan  7 22:52 filter.sqlite-shm
-rw-r--r-- 1 root root   0 Jan  7 22:52 filter.sqlite-wal
-rw-r--r-- 1 root root 12K Apr 29  2023 history.sqlite
-rw-r--r-- 1 root root 32K Jan  7 22:52 history.sqlite-shm
-rw-r--r-- 1 root root   0 Jan  7 22:52 history.sqlite-wal
-rw-r--r-- 1 root root 18K Apr 29  2023 sys.sqlite

/volume1/@SynologyDriveShareSync/log:
total 352K
drwxr-xr-x 1 root root   72 Jun  8  2020 .
drwxr-xr-x 1 root root   40 Apr 29  2023 ..
-rw-rw-rw- 1 root root 1.8K Jan  7 22:52 dscc_cgi.log
-rw-rw-rw- 1 root root 184K Jan  7 22:52 dscc.log
-rw-rw-rw- 1 root root 164K Jan  7 22:52 dscc_monitor.log

/volume1/@SynologyDriveShareSync/session:
total 0
drwxr-xr-x 1 root root  0 Jun  8  2020 .
drwxr-xr-x 1 root root 40 Apr 29  2023 ..

/volume1/@SynologyDriveShareSync/@tmp:
total 0
drwxr-xr-x 1 root root  0 Apr 29  2023 .
drwxr-xr-x 1 root root 40 Apr 29  2023 ..
```

```
root@dsm:~# ls -lah /volume2/@SynologyDriveShareSync/*
ls: cannot access '/volume2/@SynologyDriveShareSync/*': No such file or directory
```

Your Q response 2
```
root@dsm:/# ls /volume1 | grep -i '^@synologydrive'
@synologydrive
@SynologyDriveShareSync

root@dsm:/# ls /volume2 | grep -i '^@synologydrive'
@synologydrive
```

Other
```
root@dsm:/# ls /volume1 | grep -i '^@synodrive'
@SynoDrive
```
```
root@dsm:/# ls /volume2 | grep -i '^@synodrive'
@SynoDrive
```

Other 2
```
root@dsm:/# du -h --max-depth=0 /volume1/@SynoDrive/*
249M	/volume1/@SynoDrive/NoteStation
```
```
root@dsm:/# du -h --max-depth=0 /volume2/@SynoDrive/*
7.2M	/volume2/@SynoDrive/office
```

Hope this helps!

**Comment by 007revad** [comment]
I've released anew version that correctly moves Drive and it's database https://github.com/007revad/Synology_app_mover/releases/tag/v2.0.6

**Comment by sysvar** [comment]
Thank you, worked perfectly!
