### ISSUE TITLE
Small question about backup files

### ISSUE THREAD

**Issue by ChanLicher** [007revad/Synology_app_mover#98]
If I didn't setup the backup path correctly, where will the backup files go? I set a wrong path that dosen't exist, but the backup process worked fine, and I cannot find those files now.

**Comment by 007revad** [comment]
When you ran the script did you select Move or Backup?

What backup path did you set?

**Comment by ChanLicher** [comment]
> When you ran the script did you select Move or Backup?
> 
> What backup path did you set?

I choose "move", but what I want to move is Container Manager, and there is a step "Do you want ot backup the @docker...". I typed "y", and it took a long time to backup but proceeded very well.

The backup path I set is "/volume1/temp/Synology_app_mover-3.0.59/backups", but this path missed one part. 
The full correct path should be "/volume1/**SuuuperNAS**/temp/Synology_app_mover-3.0.59/backups".

By the way, I tried "find -type d" and tried to delete "@docker" and "@docker_backup" on volume1.
So, now I wonder where are those backups? Because it seems that those backups still take up like 200+ GB space.

**Comment by 007revad** [comment]
The backup path is only used when you select Backup or Restore. It's not used when you select Move.

`/volume1/@docker` should be almost empty. `/volume1/@docker_backup` is the backup. You can check their size with:
```
du -sh /volume1/@docker
```
and
```
du -sh /volume1/@docker_backup
```
Assuming you moved Container Manager to volume2 or volume3 etc you can delete `/volume1/@docker_backup` and `/volume1/@docker` with:
```
rm -rf /volume1/@docker_backup
rm -rf /volume1/@docker
```

**Comment by ChanLicher** [comment]
> The backup path is only used when you select Backup or Restore. It's not used when you select Move.
> 
> `/volume1/@docker` should be almost empty. `/volume1/@docker_backup` is the backup. You can check their size with:
> 
> ```
> du -sh /volume1/@docker
> ```
> 
> and
> 
> ```
> du -sh /volume1/@docker_backup
> ```
> 
> Assuming you moved Container Manager to volume2 or volume3 etc you can delete `/volume1/@docker_backup` and `/volume1/@docker` with:
> 
> ```
> rm -rf /volume1/@docker_backup
> rm -rf /volume1/@docker
> ```

OK, I see. Thank you! I tried these two "rm" command, maybe it is not docker that takes up my space.
